[i18n]
Title = '标题'
Description = '大纲'




[i18n.Introduction]
ID = 'ZORALab赫斯提亚许可证'
Title = "ZORALab赫斯提亚批准的许可证"




[i18n.Documentations]
ID = '官方文件'
Title = '官方文件'
Description = '''
所有在ZORALab赫斯提亚工程里需要的法治官方文件在一下的名单里一一例出。在还未运用
ZORALab赫斯提亚代码之前，请仔细的过目这些文件才决定合适。
'''


[i18n.Documentations.Labels]
Type = '类型'
PDF = 'PDF'
Signature = 'GPG文凭'
Key = 'GPG钥匙'
Coverage = '覆盖'
Examples = '例子'
Sources = "来源"




[i18n.Guidelines]
ID = '指引'
Title = '指引'
Description = '''
虽然ZORALab赫斯提亚工程允许您很广大的创意自由，它的法治官方文件还是有点敌对和冷
血的。如此一来，一方万一，我们准备了这些指引把他们容易理解：
'''

[i18n.Guidelines.Labels]
Do = '请您可以'
Dont = '请您不可以'


[[i18n.Guidelines.DO]]
Value = '''
只用ZORALab赫斯提亚工程的代码而已。完全不要用它的其他不是代码的资产（如：照片、
视频、声音、二元制、等等）。如果您有这些不是代码的资产的需求，您可以直接和在主页
例出它们的创造者联系和购买。
'''

[[i18n.Guidelines.DO]]
Value = '''
当您运用ZORALab赫斯提亚工程时归因（或加入学分）回ZORALab赫斯提亚工程。一个简单的
“谢谢ZORALab赫斯提亚”URL归因链就已经足够了。
'''

[[i18n.Guidelines.DO]]
Value = '''
可以在您的商用工程运用ZORALab赫斯提亚工程代码（如：不管是直接让顾客付款还是开源
请求赞助建设可赚钱的APP）。
'''

[[i18n.Guidelines.DO]]
Value = '''
当您参考一份有版权左派效果（如：GPL-2）的代码时，只是做：（1）阅读代码、（2）
明白它的操作算法和步骤、（3）制造操作算法和步骤的文件、（4）把原本的代码删除和忘
记掉然后就依靠那文件重新写出新的一份代码。千万不可以盲目地直接复制粘贴。
'''

[[i18n.Guidelines.DO]]
Value = '''
当您上游回馈代码时：请您确定您的回馈代码是可以直接和我们出产的许可证直接配合。我
们是无法接受完全不能使用的许可证如GPL-2、GPL-3、不详和最惨的：私人。
'''

[[i18n.Guidelines.DO]]
Value = '''
当您上游回馈代码时：请您确定所有参考的贡献者在有关代码文件的许可证通告里例入（可
以跟踪到文件出生的所有贡献者）。为了不单靠LICENSE.md而加以多层保护，我们是运行文
件级的许可证通告的。
'''

[[i18n.Guidelines.DO]]
Value = '''
当您上游回馈代码时：请您确定所有参考的贡献者的资料是在公开网络可以索取和确定的
（如：公开展览的个人网站）。大致上我们秩序要全名和可以联系的电邮地址而已。
'''

[[i18n.Guidelines.DO]]
Value = '''
如果您上游回馈代码用图画类型，我们只能接受不含任何嵌入或别地条用文件代码类而已的
SVG图画和动画文件。
'''

[[i18n.Guidelines.DO]]
Value = '''
如果您上游回馈是文件有关需要运用图画或动画，请只在免费（价钱和用法自由）的网站如
Pexels或Pixabay购买和回馈原本的创造者即使他们的许可证是非常宽容和不需要的。
'''

[[i18n.Guidelines.DO]]
Value = '''
如果您上游回馈是文件有关需要运用图画或动画: 请您确定所有的创造者的个人网站是公开
赏阅和之接确认原点资料（所有艺术有关的贡献者第一个链接是代表我们和他们的关系和他
们的产品原点)。
'''

[[i18n.Guidelines.DO]]
Value = '''
如果您上游回馈是文件有关需要运用图画或动画: 请别用拥有可以辨认的模特儿的产品（需
要为每个模特儿另外已签署的模特儿认同法治文件）。模特儿定义有包括可辨别归属的不是
人类型的动物、植物和特别法治情况如埃菲尔塔夜景的图画或动画。
'''

[[i18n.Guidelines.DO]]
Value = '''
如果在范围能力允许之内，请避免运用AI制造的图画或动画。请通过一个简简单单在主页的
回馈名单支持那些艺术者吧。
'''

[[i18n.Guidelines.DO]]
Value = '''
请您尊敬您的所以贡献者的产品、心思、登入的许可证的条款和条件、和他们的隐私。
'''

[[i18n.Guidelines.DONT]]
Value = '''
请别运用ZORALab赫斯提亚的代码然后公开地说是您的一切版权。附加说明：请别逼我们或其
他人在公开网面的猛射你啦，你这个又蠢又笨的IP强盗!
'''

[[i18n.Guidelines.DONT]]
Value = '''
请别在没有查明原点和原本的贡献者的来源下随意复制粘贴您的代码。
'''

[[i18n.Guidelines.DONT]]
Value = '''
请别用我们的sites/和artworks/目录箱里的任何图画、声音、多元媒体视频等等的文件和
资产。如果需要，请直接和在主页例出的创造者联系和购买。
'''

[[i18n.Guidelines.DONT]]
Value = '''
请别参考没有公开的工程文件（如需要购买或特别索取方式等等之类的）。我们不想把这个
麻烦推出去给下游用户。
'''

[[i18n.Guidelines.DONT]]
Value = '''
请别用拥有可以辨认的模特儿的产品（需要为每个模特儿另外已签署的模特儿认同法治文
件）。模特儿定义有包括可辨别归属的不是人类型的动物、植物和特别法治情况如埃菲尔塔
夜景的图画或动画。
'''

[[i18n.Guidelines.DONT]]
Value = '''
请别用不是免费和运用自由如需要金钱购买和不能公开分发主要条件的图画或动画。
'''

[[i18n.Guidelines.DONT]]
Value = '''
请别不尊重您的贡献者的产品、心思、登入的许可证的条款和条件、和他们的隐私。
'''




[i18n.COC]
ID = '行为准则'
Title = '行为准则'
Description = '''
这是个为代码开发者准备的代码库：不是婴儿保养中心、不是幼儿园、不是学校、不是论坛
、不是政治机构和更加不是执法实体。请自重和尊重他人。别逼我们在这儿写出长篇的人类
心理精神控制手册 ⇒ 请把您的意见和政治话哗啦啦的带去别地，谢谢。
'''




[i18n.Epilogue]
ID = '终结'
Title = '终结'
Description = '''
好啦，我们以经到了ZORALab赫斯提亚批准的许可证和一切法治文件网页的终结了。如果您
准备好了，我们已经为您预备好！请随时在以下的链接开始您的开发行程吧：
'''
URL = '/zh-hans/getting-started'
CTA = '开始指南'
