[Date]
Created = "Tue 26 Jul 2022 04:13:18 PM +08" # e.g.: "Thu 21 Jul 2022 04:27:39 PM +08"
Published = "Tue 26 Jul 2022 04:13:18 PM +08" # e.g.: "Thu 21 Jul 2022 04:27:39 PM +08"




[Content]
Title = "Render Open Graph Thumbnails HTML Metas - HestiaHUGO's Partial Function | {{ .Titles.Site -}}"
Keywords = [
	"Thumbnails",
	"Open Graph",
	"Meta",
	"HTML",
	"Render",
	"Functions",
	"Hestia",
	"Partials",
	"Layouts",
	"Specifications",
	"HestiaHUGO",
	"ZORALab's Hestia",
	"Official Website",
	"ZORALab Enterprise",
	"ZORALab",
]




[Description]
Pitch = """
Uniformly render Open Graph Thumbnails HTML metas with HestiaHUGO's
'html/meta/open-graph/Thumbnails' partial functions.
"""
Summary = """
Renders Open Graph HTML meta uniformly with HestiaHUGO's
'html/meta/open-graph/Thumbnails' internal partial function.
"""




[Redirect]
URL = ""
Delay = 0 # second
Enabled = false
