[[Components.Anchor]]
Name = "ZORALab's Hestia Anchor UI"
Pitch = '''
The ZORALab's Hestia primary "link" component used with its Core component.
'''
ID = "anchor_hestiaUI"
Thumbnail = "thumbnails-1200x1200.jpg"


[[Components.Badge]]
Name = "ZORALab's Hestia Shields.io Badge UI Component"
Pitch = '''
Now who says it needs an external server for rendering Shields.io badges.
'''
ID = "badge-shields_hestiaUI"
Thumbnail = "thumbnails-1200x1200.jpg"


[[Components.Blockquote]]
Name = "ZORALab's Hestia Blockquote UI"
Pitch = '''
Citation with clarity the ZORALab's Hestia way.
'''
ID = "blockquote_hestiaUI"
Thumbnail = "thumbnails-1200x1200.jpg"


[[Components.Button]]
Name = "ZORALab's Hestia Button UI"
Pitch = '''
Standard buttons - made by ZORALab's Hestia.
'''
ID = "button_hestiaUI"
Thumbnail = "thumbnails-1200x1200.jpg"


[[Components.Card]]
Name = "ZORALab's Hestia Card UI"
Pitch = '''
Standard cards - made by ZORALab's Hestia.
'''
ID = "card_hestiaUI"
Thumbnail = "thumbnails-1200x1200.jpg"


[[Components.Carousel]]
Name = "ZORALab's Hestia Carousel UI"
Pitch = '''
No-JS capable; Left-right scrolling; No autorun.
'''
ID = "carousel_hestiaUI"
Thumbnail = "thumbnails-1200x1200.jpg"


[[Components.Code]]
Name = "ZORALab's Hestia Code UI"
Pitch = '''
Keep the syntax and codes clean and clear!
'''
ID = "code_hestiaUI"
Thumbnail = "thumbnails-1200x1200.jpg"


[[Components.Core]]
Name = "ZORALab's Hestia Core UI"
Pitch = '''
The ZORALab's Hestia base foundation for all its complimentary components.
'''
ID = "core_hestiaUI"
Thumbnail = "thumbnails-1200x1200.jpg"


[[Components.Dialog]]
Name = "ZORALab's Hestia Dialog UI"
Pitch = '''
Intractively react with your visitor.
'''
ID = "dialog_hestiaUI"
Thumbnail = "thumbnails-1200x1200.jpg"


[[Components.Divider]]
Name = "ZORALab's Hestia Divider UI"
Pitch = '''
Standard divider for separating 2 contexts.
'''
ID = "divider_hestiaUI"
Thumbnail = "thumbnails-1200x1200.jpg"


[[Components.Divider]]
Name = "ZORALab's Hestia Cutting Divider UI"
Pitch = '''
For printout: please physically cut here.
'''
ID = "divider-cut_hestiaUI"
Thumbnail = "thumbnails-1200x1200.jpg"


[[Components.Divider]]
Name = "ZORALab's Hestia Dashed Divider UI"
Pitch = '''
For those who loves dashing around.
'''
ID = "divider-dashed_hestiaUI"
Thumbnail = "thumbnails-1200x1200.jpg"


[[Components.Font]]
Name = "ZORALab's Hestia Noto Sans Font UI"
Pitch = '''
The ZORALab's primary font for best possible communicative presentation.
'''
ID = "font-NotoSans_hestiaUI"
Thumbnail = "thumbnails-1200x1200.jpg"


[[Components.Form]]
Name = "ZORALab's Hestia Form UI"
Pitch = '''
Gathering input with great visual feedback for data accuracy.
'''
ID = "form_hestiaUI"
Thumbnail = "thumbnails-1200x1200.jpg"


[[Components.IFrame]]
Name = "ZORALab's Hestia iFrame UI"
Pitch = '''
Integrate 3rd-party sites controllably.
'''
ID = "iframe_hestiaUI"
Thumbnail = "thumbnails-1200x1200.jpg"


[[Components.List]]
Name = "ZORALab's Hestia Definitions List UI"
Pitch = '''
Defining subject systematically and scalably organized.
'''
ID = "deflist_hestiaUI"
Thumbnail = "thumbnails-1200x1200.jpg"


[[Components.List]]
Name = "ZORALab's Hestia Ordered List UI"
Pitch = '''
Keeping your points straight and scalably organized with numbering.
'''
ID = "olist_hestiaUI"
Thumbnail = "thumbnails-1200x1200.jpg"


[[Components.List]]
Name = "ZORALab's Hestia Unordered List UI"
Pitch = '''
Keeping your points straight and scalably organized with bulleting.
'''
ID = "ulist_hestiaUI"
Thumbnail = "thumbnails-1200x1200.jpg"


[[Components.Nav]]
Name = "ZORALab's Hestia Catalog Nav UI"
ID = "catalog_hestiaUI"
Pitch = '''
Who doesn't love shopping catalog style.
'''
Thumbnail = "thumbnails-1200x1200.jpg"


[[Components.Nav]]
Name = "ZORALab's Hestia Drawer UI"
Pitch = '''
The usual and responsive sidebar and topbar.
'''
ID = "drawer_hestiaUI"
Thumbnail = "thumbnails-1200x1200.jpg"


[[Components.Nav]]
Name = "ZORALab's Hestia TOC UI"
ID = "toc_hestiaUI"
Pitch = '''
Livesaver navigating through a long-winded essay.
'''
Thumbnail = "thumbnails-1200x1200.jpg"


[[Components.Note]]
Name = "ZORALab's Hestia Note UI"
Pitch = '''
Hey, there's a note for you.
'''
ID = "note_hestiaUI"
Thumbnail = "thumbnails-1200x1200.jpg"


[[Components.Note]]
Name = "ZORALab's Hestia Error Note UI"
Pitch = '''
Red alert! This note is very serious.
'''
ID = "note-error_hestiaUI"
Thumbnail = "thumbnails-1200x1200.jpg"


[[Components.Note]]
Name = "ZORALab's Hestia Warning Note UI"
Pitch = '''
Excuse me! Please attend this notice as soon as possible.
'''
ID = "note-warning_hestiaUI"
Thumbnail = "thumbnails-1200x1200.jpg"


[[Components.Note]]
Name = "ZORALab's Hestia Success Note UI"
Pitch = '''
Good News! Take a look at this note.
'''
ID = "note-success_hestiaUI"
Thumbnail = "thumbnails-1200x1200.jpg"


[[Components.Picture]]
Name = "ZORALab's Hestia Picture UI"
Pitch = '''
Confidently showcase images responsively.
'''
ID = "picture_hestiaUI"
Thumbnail = "thumbnails-1200x1200.jpg"


[[Components.Pre]]
Name = "ZORALab's Hestia Preformatted Text UI"
Pitch = '''
It's done formatting already. Just present it as it is.
'''
ID = "pre_hestiaUI"
Thumbnail = "thumbnails-1200x1200.jpg"


[[Components.Table]]
Name = "ZORALab's Hestia Table UI"
Pitch = '''
Presenting dataset clearly.
'''
ID = "table_hestiaUI"
Thumbnail = "thumbnails-1200x1200.jpg"
