[Metadata]
Name = 'Tar-GZip HestiaDOCS'
Description = """
Package ZORALab's Hestia documentation into a single .tar.gz package.
"""
Type = 'manual'




[Variables]
Product = 'docs'

[FMTVariables]
PackageDir = '{{- .WorkingDir -}}/{{- .Product -}}'
PackagePath = '{{- .WorkingDir -}}/hestiaDOCS-{{- .App.Version -}}-pack.tar.gz'


[[Dependencies]]




[Packages.001]
OS = [ 'all' ]
Arch = [ 'all' ]
Name = '{{- .Product -}}-{{- .PkgVersion -}}'
Distribution = [
	'stable',
]
BuildSource = false

[Packages.001.Files]
'{{- .PackageDir -}}/hestia' = '{{- .RootDir -}}/{{- .Product -}}'




[[CMD]]
Name = 'Delete Existing Packaging Directory if Exists'
Type = 'delete-recursive-quiet'
Condition = [ 'all-all' ]
Source = '{{ .PackageDir -}}'


[[CMD]]
Name = 'Make Packaging Directory for New Packaging Job'
Type = 'create-path'
Condition = [ 'all-all' ]
Source = '{{ .PackageDir -}}'


[[CMD]]
Name = 'Copy Source Product into Packaging Directory'
Type = 'command'
Condition = [ 'all-all' ]
Source = 'cp -r "{{- .RootDir -}}/{{- .Product -}}" "{{- .PackageDir -}}/hestia"'


[[CMD]]
Name = 'Compress into TarGz'
Type = 'command'
Condition = [ 'all-all' ]
Source = 'tar cfzv "{{- .PackagePath -}}" "{{- .PackageDir -}}"'
