[Date]
Created = "Wed 27 Jul 2022 10:23:52 AM +08" # e.g.: "Thu 21 Jul 2022 04:27:39 PM +08"
Published = "Wed 27 Jul 2022 10:23:52 AM +08" # e.g.: "Thu 21 Jul 2022 04:27:39 PM +08"




[Content]
Title = "Render Open Graph URL HTML Metas - HestiaHUGO's Partial Function | {{ .Titles.Site -}}"
Keywords = [
	"URL",
	"Open Graph",
	"Meta",
	"HTML",
	"Render",
	"Functions",
	"Hestia",
	"Partials",
	"Layouts",
	"Specifications",
	"HestiaHUGO",
	"ZORALab's Hestia",
	"Official Website",
	"ZORALab Enterprise",
	"ZORALab",
]




[Description]
Pitch = """
Uniformly render Open Graph Title URL metas with HestiaHUGO's
'html/meta/open-graph/URL' partial functions.
"""
Summary = """
Renders Open Graph HTML meta uniformly with HestiaHUGO's
'html/meta/open-graph/URL' internal partial function.
"""




[Redirect]
URL = ""
Delay = 0 # second
Enabled = false
