[assets]
dir = ':cacheDir/assets'
maxAge = -1


[getcsv]
dir = ':cacheDir/csv'
maxAge = -1


[getjson]
dir = ':cacheDir/json'
maxAge = -1


[getresource]
dir = ':cacheDir/resources'
maxAge = -1


[images]
dir = ':cacheDir/images'
maxAge = -1


[modules]
dir = ':cacheDir/modules'
maxAge = -1
