[Component]
Name = "ZORALab's Hestia Pre UI Component"
Type = "text"
ID = "pre_hestiaUI"
Status = "Stable - Public"
Available = "v0.0.1"
Purpose = """
This UI component was primarily designed for highlighting preformatted text
like a programming language snippets. It works natively so that the content
creator can focus on the writing rather than messing with the code fragment
styles.
"""
Example = """
<pre>
LINE 1:	This is a line in pure 'pre' syntax.
LINE 2:	This is another line in pure 'pre' syntax.
</pre>

<pre><code>
	<i>This paragraph is wrapped in a code syntax which looks like</i>
	<code>this</code> <i>and ends with a clean paragraph.</i>
</code></pre>
"""


[[Component.Dependencies]]
ID = "core_hestiaUI"
Priority = "Compulsory"
Include = true


[[Component.Dependencies]]
ID = "code_hestiaUI"
Priority = "Compulsory"
Include = true


[[Component.Designers]]
Name = "(Holloway) Chew, Kean Ho"
Email = "me@hollowaykeanho.com"
Website = "https://www.hollowaykeanho.com"


[Component.References]
JS = ""
Go = ""
Rust = ""


[[Component.References.HTML]]
Type = "Minimum"
Description = """
The component uses W3C compatible 'pre' syntax to render itself minimally:
"""
Example = """
<pre>...</pre>
"""


[[Component.References.HTML]]
Type = "Recommended"
Description = """
The component uses W3C compatible 'pre' syntax and have an internal 'code'
syntax to render itself in a recommended pattern:
"""
Example = """
<pre><code>
	...
</code></pre>
"""


[[Component.References.CSS]]
Name = "--pre-display"
Description = """
Affects the entire component's display mode value.
"""
Property = "display"
Default = "block"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--pre-margin"
Description = """
Affects the entire component's margin value.
"""
Property = "margin"
Default = "2rem auto"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--pre-padding"
Description = """
Affects the entire component's padding value.
"""
Property = "padding"
Default = "2rem"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--pre-overflow"
Description = """
Affects the entire component's overflow value.
"""
Property = "oveflow"
Default = "auto auto"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--pre-border"
Description = """
Affects the entire component's border value.
"""
Property = "border"
Default = ".3rem solid var(--pre-color)"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--pre-border-radius"
Description = """
Affects the entire component's border radius value.
"""
Property = "border-radius"
Default = ".5rem"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--pre-min-width"
Description = """
Affects the entire component's minimum width value.
"""
Property = "min-width"
Default = "initial"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--pre-width"
Description = """
Affects the entire component's width value.
"""
Property = "width"
Default = "80%"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--pre-max-width"
Description = """
Affects the entire component's maximum width value.
"""
Property = "max-width"
Default = "80%"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--pre-min-height"
Description = """
Affects the entire component's minimum height value.
"""
Property = "min-height"
Default = "initial"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--pre-height"
Description = """
Affects the entire component's height value.
"""
Property = "height"
Default = "initial"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--pre-max-height"
Description = """
Affects the entire component's maximum height value.
"""
Property = "max-height"
Default = "initial"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--pre-font-size"
Description = """
Affects the entire component's font size value.
"""
Property = "font-size"
Default = "var(--body-font-size)"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--pre-font-family"
Description = """
Affects the entire component's font family value.
"""
Property = "font-family"
Default = "monospace"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--pre-text-decoration"
Description = """
Affects the entire component's text decoration value.
"""
Property = "text-decoration"
Default = "normal"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--pre-word-break"
Description = """
Affects the entire component's word breaking behavior value.
"""
Property = "word-break"
Default = "keep-all"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--pre-letter-spacing"
Description = """
Affects the entire component's letter spacing value.
"""
Property = "letter-spacing"
Default = "0"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--pre-line-height"
Description = """
Affects the entire component's line height value.
"""
Property = "line-height"
Default = "var(--body-line-height)"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--pre-text-align"
Description = """
Affects the entire component's text alignment value.
"""
Property = "text-align"
Default = "justify"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--pre-white-space"
Description = """
Affects the entire component's whitespace value.
"""
Property = "white-space"
Default = "pre"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--pre-color"
Description = """
Affects the entire component's color value.
"""
Property = "color"
Default = "var(--color-primary-300)"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--pre-color-inverted"
Description = """
Affects the entire component's color value in an inverted environment
(e.g. footer).
"""
Property = "color"
Default = "var(--color-primary-300)"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--pre-color-print"
Description = """
Affects the entire component's color value in print mode.
"""
Property = "color"
Default = "var(--body-color-print)"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--pre-background"
Description = """
Affects the entire component's background value.
"""
Property = "background"
Default = "var(--color-contrast-50)"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--pre-background-inverted"
Description = """
Affects the entire component's background value in an inverted environment
(e.g. footer).
"""
Property = "background"
Default = "var(--color-contrast-50)"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--pre-background-print"
Description = """
Affects the entire component's background value in print mode.
"""
Property = "background"
Default = "var(--body-background-print)"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--pre-transition"
Description = """
Affects the entire component's animation timing value.
"""
Property = "transition"
Default = "var(--timing-rapid)"
Availability = "v0.0.1"
