# HESTIA WEB UI COMPONENTS LIST (PAGE SPECIFIC)
# =============================================
# All Hestia internal web UI components page specific configurations. ONLY
# include those you need/override. See .Data.Hestia.Components data file for
# helper.
