# HESTIA PAGE-LEVEL WEB UI COMPONENTS LIST
# ========================================
# All Hestia internal web UI components at page-level specific configurations.
# ONLY include/exclude those you need/unused. See .Data.Hestia.Components data
# file for help.
