# Hestia PAGE-LEVEL thumbnails configurations
# -------------------------------------------
# By default, Hestia supplies 3 dataset of thumbnails the 1200x630, 480x480, and
# 1200x1200 JPEG format images mainly used across social network via OpenGraph
# or their own requirements. All you need to do is to prepare these thumbnails
# and place it inside your page-level directory according to the URL name.
#
# Each image complies to the Hestia's Media data structure for image.
#
# Hugo's and Go's data processor is available in case you want to fill in a
# dynamic data.
#
# Although the configurations permit multiple sources, only the first source
# is selected for rendering in the case of OpenGraph. For specialized thumbnail
# requirement, a built-in aspect ratio detection algorithm shall be ran to
# select the best suitable thumbnail matching the requirement.
[Contents.0]
Name = '{{- .Titles.Page -}}'
Decorative = false
Loading = 'lazy'
Width = '1200'
Height = '630'
CORS = ''
Relationship = ''
Design = ''
Preload = ''
Control = false
Autoplay = false
Loop = false
Mute = false
Inline = false

[[Contents.0.Sources]]
URL = 'thumbnails-1200x630.jpg'
Type = 'image/jpeg'
Media = 'all'
Descriptor = '1x'

[Contents.0.Tracks.en]
URL = ''
Kind = 'subtitles'
Label = 'English'
Default = false




[Contents.1]
Name = '{{- .Titles.Page -}}'
Decorative = false
Loading = 'lazy'
Width = '1200'
Height = '1200'
CORS = ''
Relationship = ''
Design = ''
Preload = ''
Control = false
Autoplay = false
Loop = false
Mute = false
Inline = false

[[Contents.1.Sources]]
URL = 'thumbnails-1200x1200.jpg'
Type = 'image/jpeg'
Media = 'all'
Descriptor = '1x'

[Contents.1.Tracks.en]
URL = ''
Kind = 'subtitles'
Label = 'English'
Default = false




[Contents.2]
Name = '{{- .Titles.Page -}}'
Decorative = false
Loading = 'lazy'
Width = '480'
Height = '480'
CORS = ''
Relationship = ''
Design = ''
Preload = ''
Control = false
Autoplay = false
Loop = false
Mute = false
Inline = false

[[Contents.2.Sources]]
URL = 'thumbnails-480x480.jpg'
Type = 'image/jpeg'
Media = 'all'
Descriptor = '1x'

[Contents.2.Tracks.en]
URL = ''
Kind = 'subtitles'
Label = 'English'
Default = false
