[Date]
Created = "Tue 26 Jul 2022 11:44:03 AM +08" # e.g.: "Thu 21 Jul 2022 04:27:39 PM +08"
Published = "Tue 26 Jul 2022 11:44:03 AM +08" # e.g.: "Thu 21 Jul 2022 04:27:39 PM +08"




[Content]
Title = "Render Hestia HTML Debug Interface - HestiaHUGO's Partial Function | {{ .Titles.Site -}}"
Keywords = [
	"Debug",
	"HTML",
	"Render",
	"Functions",
	"Hestia",
	"Partials",
	"Layouts",
	"Specifications",
	"HestiaHUGO",
	"ZORALab's Hestia",
	"Official Website",
	"ZORALab Enterprise",
	"ZORALab",
]




[Description]
Pitch = """
Uniformly render Hestia debug interfaces with HestiaHUGO's 'html/debug'
functions.
"""
Summary = """
Renders Hestia debug interfaces uniformly with HestiaHUGO's 'html/debug'
internal partial functions.
"""




[Redirect]
URL = ""
Delay = 0 # second
Enabled = false
