[Component]
Name = "ZORALab's Hestia Table of Contents UI Component"
Type = "nav"
ID = "toc_hestiaUI"
Status = "Stable - Public"
Available = "v1.0.0"
Purpose = """
This UI component was primarily designed for tabulating a list of navigational
materials like jumping anchor links. It is meant for reader's ability to jump
to a section of interest easily. The component works natively without having
complicated CSS classing, Javascript, or WASM intervention and assistances. It
is only responsible for layout orientation so the developer can have full
freedom to fill its content.
"""
Example = """
<nav class='toc'>
	<p>Item 1</p>
	<p>Item 2</p>
	<p>Item 3</p>
</nav>
"""

[[Component.Dependencies]]
ID = "core_hestiaUI"
Priority = "Compulsory"
Include = true


[[Component.Designers]]
Name = "(Holloway) Chew, Kean Ho"
Email = "me@hollowaykeanho.com"
Website = "https://www.hollowaykeanho.com"


[Component.References]
JS = ""
Go = ""
Rust = ""


[[Component.References.HTML]]
Type = "Minimum"
Description = """
The component uses W3C compatible 'nav' syntax with '.toc' CSS class to render
itself minimally:
"""
Example = """
<nav class='toc'>
	...
</nav>
"""

[[Component.References.CSS]]
Name = "--toc-margin"
Description = "Affects the entire component's margin value."
Property = "margin"
Default = "2rem auto"
Availability = "v1.0.0"

[[Component.References.CSS]]
Name = "--toc-padding"
Description = "Affects the entire component's padding value."
Property = "padding"
Default = "2rem"
Availability = "v1.0.0"

[[Component.References.CSS]]
Name = "--toc-min-width"
Description = "Affects the entire component's minimum width value."
Property = "min-width"
Default = "20rem"
Availability = "v1.0.0"

[[Component.References.CSS]]
Name = "--toc-width"
Description = "Affects the entire component's width value."
Property = "width"
Default = "fit-content"
Availability = "v1.0.0"

[[Component.References.CSS]]
Name = "--toc-max-width"
Description = "Affects the entire component's maximum width value."
Property = "max-width"
Default = "100%"
Availability = "v1.0.0"

[[Component.References.CSS]]
Name = "--toc-min-height"
Description = "Affects the entire component's minimum height value."
Property = "min-height"
Default = "initial"
Availability = "v1.0.0"

[[Component.References.CSS]]
Name = "--toc-height"
Description = "Affects the entire component's height value."
Property = "height"
Default = "fit-content"
Availability = "v1.0.0"

[[Component.References.CSS]]
Name = "--toc-max-height"
Description = "Affects the entire component's maximum height value."
Property = "max-height"
Default = "initial"
Availability = "v1.0.0"

[[Component.References.CSS]]
Name = "--toc-border"
Description = "Affects the entire component's border value."
Property = "border"
Default = "initial"
Availability = "v1.0.0"

[[Component.References.CSS]]
Name = "--toc-border-radius"
Description = "Affects the entire component's border radius value."
Property = "border-radius"
Default = ".5rem"
Availability = "v1.0.0"

[[Component.References.CSS]]
Name = "--toc-color"
Description = "Affects the entire component's color value."
Property = "color"
Default = "var(--body-color)"
Availability = "v1.0.0"

[[Component.References.CSS]]
Name = "--toc-color-inverted"
Description = """
Affects the entire component's color value in inverted environment (e.g. footer).
"""
Property = "color"
Default = "var(--body-color-inverted)"
Availability = "v1.0.0"

[[Component.References.CSS]]
Name = "--toc-color-print"
Description = "Affects the entire component's color value in print mode."
Property = "color"
Default = "var(--body-color-print)"
Availability = "v1.0.0"

[[Component.References.CSS]]
Name = "--toc-background"
Description = "Affects the entire component's background value."
Property = "background"
Default = "transparent"
Availability = "v1.0.0"

[[Component.References.CSS]]
Name = "--toc-background-inverted"
Description = """
Affects the entire component's background value in inverted environment (e.g. footer).
"""
Property = "background"
Default = "transparent"
Availability = "v1.0.0"

[[Component.References.CSS]]
Name = "--toc-background-print"
Description = "Affects the entire component's color value in print mode."
Property = "background"
Default = "transparent"
Availability = "v1.0.0"

[[Component.References.CSS]]
Name = "--toc-content-margin"
Description = "Affects the component's content container's margin value."
Property = "margin"
Default = "2rem auto"
Availability = "v1.0.0"

[[Component.References.CSS]]
Name = "--toc-content-min-width"
Description = "Affects the component's content container's min-width value."
Property = "min-width"
Default = "initial"
Availability = "v1.0.0"

[[Component.References.CSS]]
Name = "--toc-content-width"
Description = "Affects the component's content container's width value."
Property = "width"
Default = "fit-content"
Availability = "v1.0.0"

[[Component.References.CSS]]
Name = "--toc-content-max-width"
Description = "Affects the component's content container's max-width value."
Property = "max-width"
Default = "initial"
Availability = "v1.0.0"

[[Component.References.CSS]]
Name = "--toc-content-min-height"
Description = "Affects the component's content container's min-height value."
Property = "min-height"
Default = "initial"
Availability = "v1.0.0"

[[Component.References.CSS]]
Name = "--toc-content-height"
Description = "Affects the component's content container's height value."
Property = "height"
Default = "initial"
Availability = "v1.0.0"

[[Component.References.CSS]]
Name = "--toc-content-max-height"
Description = "Affects the component's content container's max-height value."
Property = "max-height"
Default = "initial"
Availability = "v1.0.0"

[[Component.References.CSS]]
Name = "--toc-title-content"
Description = """
Affects the component's title's content value. Please note that the cancelled
quotes are required and are inclusive with the actual value.
"""
Property = "content"
Default = '\"Synopsis\"'
Availability = "v1.0.0"

[[Component.References.CSS]]
Name = "--toc-title-margin"
Description = "Affects the component's title's margin value."
Property = "margin"
Default = "0 auto 2.5rem"
Availability = "v1.0.0"

[[Component.References.CSS]]
Name = "--toc-title-padding"
Description = "Affects the component's title's padding value."
Property = "padding"
Default = "0"
Availability = "v1.0.0"

[[Component.References.CSS]]
Name = "--toc-title-font-size"
Description = "Affects the component's title's font-size value."
Property = "font-size"
Default = "2rem"
Availability = "v1.0.0"

[[Component.References.CSS]]
Name = "--toc-title-font-weight"
Description = "Affects the component's title's font-weight value."
Property = "font-weight"
Default = "600"
Availability = "v1.0.0"

[[Component.References.CSS]]
Name = "--toc-title-color"
Description = "Affects the component's title's color value."
Property = "color"
Default = "var(--toc-color)"
Availability = "v1.0.0"

[[Component.References.CSS]]
Name = "--toc-title-color-inverted"
Description = """
Affects the component's title's color value in inverted environment (e.g. footer).
"""
Property = "color"
Default = "var(--toc-color-inverted)"
Availability = "v1.0.0"

[[Component.References.CSS]]
Name = "--toc-title-background"
Description = "Affects the component's title's background value."
Property = "background"
Default = "transparent"
Availability = "v1.0.0"

[[Component.References.CSS]]
Name = "--toc-title-background-inverted"
Description = """
Affects the component's title's background value in inverted environment (e.g. footer).
"""
Property = "background"
Default = "transparent"
Availability = "v1.0.0"
