[CSS.Variables]
"--anchor-display" = "inline-block"

"--anchor-min-width" = "initial"
"--anchor-width" = "initial"
"--anchor-max-width" = "initial"
"--anchor-min-height" = "initial"
"--anchor-height" = "initial"
"--anchor-max-height" = "initial"

"--anchor-margin" = "initial"
"--anchor-padding" = "0 .3rem"
"--anchor-padding-focus" = "0 .3rem"

"--anchor-border" = "initial"
"--anchor-border-top" = "2px solid transparent"
"--anchor-border-left" = "initial"
"--anchor-border-bottom" = "2px solid var(--anchor-color)"
"--anchor-border-right" = "initial"

"--anchor-font-size" = "var(--body-font-size)"
"--anchor-font-family" = "var(--body-font-family)"
"--anchor-font-weight" = "initial"
"--anchor-text-decoration" = "none"
"--anchor-text-transform" = "normal"
"--anchor-overflow-wrap" = "break-word"
"--anchor-overflow-wrap-print" = "break-word"
"--anchor-word-break" = "break-word"
"--anchor-word-break-print" = "break-word"
"--anchor-letter-spacing" = "initial"
"--anchor-line-height" = "var(--body-line-height)"
"--anchor-text-align" = "initial"

"--anchor-color" = "var(--color-primary-300)"
"--anchor-color-inverted" = "var(--color-primary-200)"
"--anchor-color-focus" = "var(--color-primary-400)"
"--anchor-color-focus-inverted" = "var(--color-primary-50)"
"--anchor-color-print" = "var(--body-color-print)"
"--anchor-text-decoration-color" = "initial"
"--anchor-text-decoration-color-inverted" = "initial"
"--anchor-background" = "transparent"
"--anchor-background-inverted" = "transparent"
"--anchor-background-focus" = "var(--body-background)"
"--anchor-background-focus-inverted" = "var(--body-background-inverted)"
"--anchor-background-print" = "transparent"
"--anchor-box-shadow" = "0 .5rem 1rem transparent"
"--anchor-box-shadow-focus" = "0 .5rem 1rem var(--color-typography-800)"
"--anchor-box-shadow-focus-inverted" = "0 .5rem 1rem var(--color-typography-200)"

"--anchor-transition" = "var(--timing-rapid)"
"--anchor-transform-focus" = "scale(1.1)"




"--anchor-prestige-font-weight" = "800"
"--anchor-prestige-text-transform" = "uppercase"

"--anchor-prestige-color-focus" = "var(--color-contrast-300)"
"--anchor-prestige-background" = "transparent"
"--anchor-prestige-background-focus" = "transparent"
