[CSS.Variables]
"--blockquote-display" = "block"
"--blockquote-before-content" = "\"❝\""

"--blockquote-margin" = "0 0 3rem"
"--blockquote-padding" = "4rem 3rem 3rem 10rem"

"--blockquote-min-width" = "initial"
"--blockquote-width" = "initial"
"--blockquote-max-width" = "initial"
"--blockquote-min-height" = "initial"
"--blockquote-height" = "initial"
"--blockquote-max-height" = "initial"

"--blockquote-text-align" = "justify"

"--blockquote-border-radius" = "1rem"

"--blockquote-color" = "var(--color-typography-900)"
"--blockquote-background" = "var(--color-typography-100)"
"--blockquote-color-shadow" = "var(--color-typography-100)"

"--blockquote-timing" = "var(--timing-rapid)"



"--blockquote-cite-margin" = "2rem 0 0"
"--blockquote-cite-border-top" = "2px solid var(--blockquote-color)"
