[CSS.Variables]
"--blockquote-color" = "var(--color-typography-900)"
"--blockquote-background" = "var(--color-typography-200)"
"--blockquote-color-shadow" = "var(--color-typography-100)"
"--blockquote-timing" = "var(--timing-rapid)"
"--blockquote-before-content" = "\"❝\""
"--blockquote-margin" = "0 0 3rem"
"--blockquote-border-radius" = "1rem"
"--blockquote-text-align" = "justify"
"--blockquote-cite-margin" = "2rem 0 0"
"--blockquote-cite-border-top" = "2px solid var(--blockquote-color)"
"--blockquote-min-width" = "initial"
"--blockquote-width" = "initial"
"--blockquote-max-width" = "initial"
"--blockquote-min-height" = "initial"
"--blockquote-height" = "initial"
"--blockquote-max-height" = "initial"
