[CSS.Variables]
"--catalog-margin" = "2rem auto"
"--catalog-padding" = "2rem"

"--catalog-min-width" = "initial"
"--catalog-width" = "fit-content"
"--catalog-max-width" = "initial"
"--catalog-min-height" = "initial"
"--catalog-height" = "fit-content"
"--catalog-max-height" = "initial"

"--catalog-border" = "1px solid transparent"
"--catalog-border-inverted" = "1px solid transparent"
"--catalog-border-print" = "1px solid var(--catalog-color-print)"
"--catalog-border-radius" = ".5rem"

"--catalog-color" = "var(--body-color)"
"--catalog-color-inverted" = "var(--body-color-inverted)"
"--catalog-color-print" = "var(--body-color-print)"
"--catalog-background" = "var(--body-background)"
"--catalog-background-inverted" = "var(--body-background-inverted)"
"--catalog-background-print" = "var(--body-background-print)"
