[CSS.Variables]
"--divider-display" = "block"

"--divider-margin" = "0 auto"
"--divider-padding" = "0"

"--divider-border" = "initial"
"--divider-border-top" = "initial"
"--divider-border-bottom" = "1px solid var(--divider-color)"

"--divider-color" = "var(--color-primary-600)"
"--divider-color-inverted" = "var(--color-primary-300)"
"--divider-background" = "transparent"
"--divider-background-inverted" = "transparent"
"--divider-border-color" = "var(--divider-color)"
"--divider-border-color-inverted" = "var(--divider-color-inverted)"
