[CSS.Variables]
"--color-red-50" = "#ffc4c4"
"--color-red-100" = "#ff9d9d"
"--color-red-200" = "#ff7676"
"--color-red-300" = "#ff4e4e"
"--color-red-400" = "#ff2727"
"--color-red-500" = "#ff0000"
"--color-red-600" = "#c40000"
"--color-red-700" = "#890000"
"--color-red-800" = "#620000"
"--color-red-900" = "#3b0000"
"--color-red-950" = "#140000"
