[CSS.Variables]
"--note-title-success-border-color" = "var(--body-color-indicator-green-inverted)"
"--note-title-success-color" = "#fff"
"--note-title-success-indicator-color" = "#fff"
"--note-title-success-background" = "var(--body-background-indicator-green-inverted)"
"--note-content-success-color" = "var(--body-color-indicator-green-inverted)"
"--note-content-success-background" = "var(--body-background-indicator-green)"
