[CSS.Variables]
"--pre-display" = "block"
"--pre-margin" = "2rem auto"
"--pre-padding" = "2rem"
"--pre-overflow" = "auto auto"
"--pre-border" = ".3rem solid var(--pre-color)"
"--pre-border-radius" = ".5rem"
"--pre-min-width" = "initial"
"--pre-width" = "100%"
"--pre-max-width" = "75vw"
"--pre-min-height" = "initial"
"--pre-height" = "initial"
"--pre-max-height" = "initial"
"--pre-color" = "var(--color-primary-600)"
"--pre-background" = "var(--color-contrast-50)"
"--pre-font-size" = "var(--body-font-size)"
"--pre-font-family" = "monospace"
"--pre-text-decoration" = "normal"
"--pre-word-break" = "keep-all"
"--pre-letter-spacing" = 0
"--pre-line-height" = "var(--body-line-height)"
"--pre-text-align" = "justify"
"--pre-transition" = "var(--timing-rapid)"
