[CSS.Variables]
"--ulist-display" = "block"
"--ulist-margin" = "0"
"--ulist-padding" = "0"
"--ulist-text-align" = "left"



"--ulist-spacing" = "2rem"
"--ulist-li-margin" = "var(--ulist-spacing) 0"
"--ulist-li-padding" = "0"




"--ulist-li-before-content" = "\"Î¨\""
"--ulist-li-before-display" = "block"

"--ulist-li-before-size" = "3rem"

"--ulist-li-before-margin" = ".5rem 1rem"
"--ulist-li-before-padding" = "0"

"--ulist-li-before-border" = "1px solid transparent"
"--ulist-li-before-border-radius" = "50%"

"--ulist-li-before-font-size" = "2rem"
"--ulist-li-before-font-weight" = "700"
"--ulist-li-before-text-align" = "center"

"--ulist-li-before-color" = "var(--color-typography-50)"
"--ulist-li-before-color-inverted" = "var(--color-contrast-50)"
"--ulist-li-before-color-print" = "var(--body-color-print)"
"--ulist-li-before-background" = "var(--color-primary-400)"
"--ulist-li-before-background-inverted" = "var(--color-primary-400)"
"--ulist-li-before-background-print" = "var(--body-background-print)"
