[CSS.Variables]
"--olist-spacing" = "4rem"




"--olist-display" = "block"

"--olist-margin" = "0 auto"
"--olist-padding" = "0"

"--olist-text-align" = "left"




"--olist-li-margin" = "var(--olist-spacing) 0"
"--olist-li-padding" = "0"


"--olist-li-before-margin" = "0"
"--olist-li-before-padding" = "0"
"--olist-li-before-font-size" = "2rem"
"--olist-li-before-font-weight" = "700"
"--olist-li-before-text-align" = "left"
