[CSS.Variables]
"--iframe-display" = "block"

"--iframe-margin" = "0 auto"

"--iframe-min-width" = "initial"
"--iframe-width-hidden" = "1px"
"--iframe-max-width" = "100%"
"--iframe-min-height" = "initial"
"--iframe-height-hidden" = "1px"
"--iframe-max-height" = "initial"

"--iframe-border" = "none"

"--iframe-background" = "inherit"

"--iframe-visibility" = "visible"
"--iframe-visibility-hidden" = "hidden"
