[Date]
Created = "Mon 25 Jul 2022 09:54:02 AM +08" # e.g.: "Thu 21 Jul 2022 04:27:39 PM +08"
Published = "Mon 25 Jul 2022 09:54:02 AM +08" # e.g.: "Thu 21 Jul 2022 04:27:39 PM +08"




[Content]
Title = "Templates - Hestia Internal Partial Function | {{ .Titles.Site -}}"
Keywords = [
	"Templates",
	"Hestia",
	"Partials",
	"Layouts",
	"Specifications",
	"HestiaHUGO",
	"ZORALab's Hestia",
	"Official Website",
	"ZORALab Enterprise",
	"ZORALab",
]




[Description]
Pitch = """
Consistent content page rendering with HestiaHugo's internal template partial
functions.
"""
Summary = """
Make consistent content page rendering with HestiaHugo's internal template
partial functions.
"""




[Redirect]
URL = ""
Delay = 0 # second
Enabled = false
