[Component]
Name = "ZORALab's Hestia Carousel UI Component"
Type = "carousel"
ID = "carousel_hestiaUI"
Status = "Stable - Public"
Available = "v0.0.1"
Purpose = """
This UI component was primarily designed for displaying multiple contents in a
same-sized, same-position viewing space. It was meant for dynamic content
decorations or multiple contexts content presentation for reader to digest. The
component works natively without having complicated CSS classing, Javascript, or
WASM intervention and assistances. It is only responsible for layout orientation
so the developer can have full freedom to fill its content. However, this
component does not have auto-run feature for the sake of working in a
Javascript-disabled environment.
"""
Example = """
<div class="carousel">
	<div class="viewport">
		<div>
			<input id="carousel1-slide1" name="carousel1" type="radio" checked />
			<div class="content" style="background: red">
				<p style='text-align: center;'>Slide 1</p>
			</div>
			<nav class="nav">
				<label class="previous" for="carousel1-slide3">❮</label>
				<label class="next" for="carousel1-slide2">❯</label>
			</nav>
		</div>


		<div>
			<input id="carousel1-slide2" name="carousel1" type="radio" />
			<div class="content" style="background: green">
				<p style='text-align: center;'>Slide 2</p>
			</div>
			<nav class="nav">
				<label class="previous" for="carousel1-slide1">❮</label>
				<label class="next" for="carousel1-slide3">❯</label>
			</nav>
		</div>


		<div>
			<input id="carousel1-slide3" name="carousel1" type="radio" />
			<div class="content" style="background: blue">
				<p style='text-align: center;'>Slide 3</p>
			</div>
			<nav class="nav">
				<label class="previous" for="carousel1-slide2">❮</label>
				<label class="next" for="carousel1-slide1">❯</label>
			</nav>
		</div>
	</div>


	<div class="panel">
		<label for="carousel1-slide1">1</label>
		<label for="carousel1-slide2">2</label>
		<label for="carousel1-slide3">3</label>
	</div>
</div>
"""


[[Component.Dependencies]]
ID = "core_hestiaUI"
Priority = "Compulsory"
Include = true


[[Component.Designers]]
Name = "(Holloway) Chew, Kean Ho"
Email = "me@hollowaykeanho.com"
Website = "https://www.hollowaykeanho.com"


[Component.References]
JS = ""
Go = ""
Rust = ""


[[Component.References.HTML]]
Type = "Minimum"
Description = """
To ensure carousel works on Javascript disabled environment, this component
exclusively and exhausively uses flexbox display; relational label and
radio-type input; and anchor ID jumping intensively to perform carousel
presentation between slices. It uses '.carousel' CSS class as its primary
notation; then a compulsory '.viewport' and an optional '.panel' CSS classes to
denote primary display parts; and lastly, within the viewport holds the
radio-type input as a slide trigger, a '.content' CSS class to denote a slide's
content, and a '.nav' CSS class to denote internal slide navigation with
'.previous' and '.next' CSS classes for differenciating their respective
positions.

As such, the minimal code structure is shown as follows:
"""
Example = """
<div class="carousel">
	<div class="viewport">
		<div>
			<input id="...slideID-1..." name="carousel1" type="radio" checked />

			<div class="content">
				...
			</div>

			<nav class="nav">
				<label class="previous" for="...slideID-LAST...">❮</label>
				<label class="next" for="...slideID-2...">❯</label>
			</nav>
		</div>


		<div>
			<input id="...slideID-2..." name="carousel2" type="radio" />

			<div class="content">
				...
			</div>

			<nav class="nav">
				<label class="previous" for="...slideID-1...">❮</label>
				<label class="next" for="...slideID-3...">❯</label>
			</nav>
		</div>

		...
	</div>


	<div class="panel">
		<label for="...slideID-1...">1</label>
		<label for="...slideID-2...">2</label>
		...
	</div>
</div>
"""

[[Component.References.CSS]]
Name = "--carousel-min-width"
Description = """
Affects the entire component's minimum width value.
"""
Property = "min-width"
Default = "initial"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-width"
Description = """
Affects the entire component's width value.
"""
Property = "width"
Default = "100%"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-max-width"
Description = """
Affects the entire component's maximum width value.
"""
Property = "max-width"
Default = "100%"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-min-height"
Description = """
Affects the entire component's minimum height value.
"""
Property = "min-height"
Default = "40rem"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-height"
Description = """
Affects the entire component's height value.
"""
Property = "height"
Default = "40rem"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-max-height"
Description = """
Affects the entire component's maximum height value.
"""
Property = "max-height"
Default = "initial"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-margin"
Description = """
Affects the entire component's margin value.
"""
Property = "margin"
Default = "2rem auto"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-padding"
Description = """
Affects the entire component's padding value.
"""
Property = "padding"
Default = "0"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-color"
Description = """
Affects the entire component's color value.
"""
Property = "color"
Default = "var(--body-color-inverted)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-background"
Description = """
Affects the entire component's background value.
"""
Property = "background"
Default = "transparent"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-perspective"
Description = """
Affects the entire component's perspective value.
"""
Property = "perspective"
Default = "2rem"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-timing"
Description = """
Affects the entire component's animation timing value.
"""
Property = "transition"
Default = "var(--timing-normal)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-nav-grid"
Description = """
Affects the component's '.content's slide navigation layout value.
"""
Property = "grid"
Default = """
"carousel-nav-prev    content    carousel-nav-next" 100%
/ max-content         auto       max-content
"""
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-nav-justify-items"
Description = """
Affects the component's '.content's slide navigation justify-items value.
"""
Property = "justify-items"
Default = "center"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-nav-align-items"
Description = """
Affects the component's '.content's slide navigation align-items value.
"""
Property = "align-items"
Default = "center"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-nav-width"
Description = """
Affects the component's '.content's slide navigation width value.
"""
Property = "width"
Default = "10rem"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-nav-height"
Description = """
Affects the component's '.content's slide navigation height value.
"""
Property = "height"
Default = "100%"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-nav-color"
Description = """
Affects the component's '.content's slide navigation color value.
"""
Property = "color"
Default = "var(--carousel-color)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-nav-background"
Description = """
Affects the component's '.content's slide navigation background value.
"""
Property = "background"
Default = "transparent"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-nav-transition"
Description = """
Affects the component's '.content's slide navigation transition value.
"""
Property = "transition"
Default = "var(--timing-rapid)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-panel-justify-content"
Description = """
Affects the component's '.panel' justify-content value.
"""
Property = "justify-content"
Default = "center"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-panel-align-content"
Description = """
Affects the component's '.panel' align-content value.
"""
Property = "align-content"
Default = "center"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-panel-align-items"
Description = """
Affects the component's '.panel' align-items value.
"""
Property = "align-items"
Default = "flex-end"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-panel-flex-direction"
Description = """
Affects the component's '.panel' flex-direction value.
"""
Property = "flex-direction"
Default = "row"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-panel-flex-wrap"
Description = """
Affects the component's '.panel' flex-wrap value.
"""
Property = "flex-wrap"
Default = "nowrap"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-panel-width"
Description = """
Affects the component's '.panel' width value.
"""
Property = "width"
Default = "100%"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-panel-height"
Description = """
Affects the component's '.panel' height value.
"""
Property = "height"
Default = "fit-content"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-panel-margin"
Description = """
Affects the component's '.panel' margin value.
"""
Property = "margin"
Default = "0"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-panel-padding"
Description = """
Affects the component's '.panel' padding value.
"""
Property = "padding"
Default = "0"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-panel-border"
Description = """
Affects the component's '.panel' border value.
"""
Property = "border"
Default = "none"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-panel-border-radius"
Description = """
Affects the component's '.panel' border-radius value.
"""
Property = "border-radius"
Default = ".5rem"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-panel-position-top"
Description = """
Affects the component's '.panel' top position value.
"""
Property = "top"
Default = "unset"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-panel-position-left"
Description = """
Affects the component's '.panel' left position value.
"""
Property = "left"
Default = "50%"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-panel-position-right"
Description = """
Affects the component's '.panel' right position value.
"""
Property = "right"
Default = "unset"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-panel-position-bottom"
Description = """
Affects the component's '.panel' bottom position value.
"""
Property = "bottom"
Default = "0"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-panel-transform"
Description = """
Affects the component's '.panel' transformation value.
"""
Property = "transform"
Default = "translateX(-50%)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-panel-color"
Description = """
Affects the component's '.panel' color value.
"""
Property = "color"
Default = "var(--carousel-color)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-panel-background"
Description = """
Affects the component's '.panel' background value.
"""
Property = "background"
Default = "transparent"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-panel-item-margin"
Description = """
Affects the component's '.panel's items margin value.
"""
Property = "margin"
Default = "0 1rem"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-panel-item-padding"
Description = """
Affects the component's '.panel's items padding value.
"""
Property = "padding"
Default = "0"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-panel-item-color"
Description = """
Affects the component's '.panel's items color value.
"""
Property = "color"
Default = "var(--carousel-color)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--carousel-panel-item-background"
Description = """
Affects the component's '.panel's items background value.
"""
Property = "background"
Default = "transparent"
Availability = "v0.0.1"
