[Component]
Name = "ZORALab's Hestia Picture UI Component"
Type = "image"
ID = "picture_hestiaUI"
Status = "Stable - Public"
Available = "v0.0.1"
Purpose = """
This UI component was primarily designed for displaying images on a web page
responsively towards the viewer's browser size. The goal is to make sure any
visitor can browse the page seamlessly without needing extra configurations.
"""
Example = """
<picture>
	<source srcset="/banner-1200x630.png 1x,
			/favicon-1200x1200.png 2x,
			/favicon-480x480.png 3x"
		type="image/png"
		media"(max-width: 200px)">
	<img alt="Sample Banner"
		src="/banner-480x480.png"
		width="1200"
		height="630"
		loading="lazy"/>
</picture>
"""


[[Component.Dependencies]]
ID = "core_hestiaUI"
Priority = "Compulsory"
Include = true


[[Component.Designers]]
Name = "(Holloway) Chew, Kean Ho"
Email = "me@hollowaykeanho.com"
Website = "https://www.hollowaykeanho.com"


[Component.References]
JS = ""
Go = ""
Rust = ""


[[Component.References.HTML]]
Type = "Minimum"
Description = """
The component uses W3C compatible 'picture' syntax to render itself minimally
for responsive display (various images for different display sizes (e.g.
horizontal and portrait) on the same page. The picture syntax is favored mainly
for consistency between media types like video and audio and responsiveness'
availability. Here is the minimum HTML template that caters different sizes and
resolutions:
"""
Example = """
<picture>
	<source srcset="... 1x,
			... 2x,
			... 3x"
		type="image/webp"
		width="1200" height="630"
		media"(max-width: ...)">     <!-- modern-format -->
	<source srcset="... 1x,
			... 2x,
			... 3x"
		type="image/..."
		width="1200" height="630"
		media"(max-width: ...)">     <!-- fallback-format -->
	<img alt="..." src="..."
		width="1200" height="630"
		loading="lazy"/>
</picture>
"""


[[Component.References.CSS]]
Name = "--picture-display"
Description = "Affects the entire component's display mode value."
Property = "display"
Default = "block"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--picture-margin"
Description = "Affects the entire component's margin value."
Property = "margin"
Default = "2rem auto"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--picture-padding"
Description = "Affects the entire component's padding value."
Property = "padding"
Default = "0"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--picture-min-width"
Description = "Affects the entire component's minimum width value."
Property = "min-width"
Default = "initial"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--picture-max-width"
Description = "Affects the entire component's maximum width value."
Property = "max-width"
Default = "100%"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--picture-min-height"
Description = "Affects the entire component's minimum height value."
Property = "min-height"
Default = "initial"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--picture-max-height"
Description = "Affects the entire component's maximum height value."
Property = "max-height"
Default = "initial"
Availability = "v0.0.1"
