baseURL = "https://www.example.com"
canonifyURLs = true
buildDrafts = false
buildExpired = false
buildFuture = false
theme = [ "hestiaHUGO" ]
metaDataFormat = "toml"
paginate = 10
summaryLength = 70
sectionPagesMenu = "sections"
enableEmoji = true
pluralizeListTitles = false
enableGitInfo = true
enableRobotsTXT = true
hasCJKLanguage = true


# content pathing
archetypeDir = "archetypes"
contentDir = "../../docs"
assetDir = "assets"
dataDir = "../../docs/.data"
staticDir = [ "../../docs/.static" ]
layoutDir = "layouts"
themesDir = "../../"
publishDir = "../../public"
i18nDir = "i18n"


# Hugo injected generator as first line and broke HTML spec. Therefore, Hestia
# disables it and inject later using its renderer.
disableHugoGeneratorInject = true


# AMP disallowed javascript loading. Also, Hugo injects it as second line and
# broke its HTML spec. Therefore, Hestia disables it and inject the liveReload
# in appropriate output using its renderer.
disableLiveReload = true
