["text/amphtml"]
suffixes = [ "amp.html" ]

["application/json"]
suffixes = [ "json" ]

["application/manifest+json"]
suffixes = [ "webmanifest" ]

["application/xml-index"]
suffixes = [ "sitemap.xml" ]

["application/xml-page"]
suffixes = [ "sitemap-page.xml" ]
