[Component]
Name = "ZORALab's Hestia Table UI Component"
Type = "table"
ID = "table_hestiaUI"
Status = "Stable - Public"
Available = "v1.0.0"
Purpose = """
This UI component was primarily designed for displaying tabulated data in
a visually meaninful and interactive way. It works natively so that the
content creator can focus on the writing rather than messing with styling.
"""
Example = """
<div style='display:flex;justify-content:center;'><table>
	<thead>
		<tr>
			<th></th>
			<th>Alpha</th>
			<th>Bravo</th>
			<th>Charlie</th>
			<th>Delta</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<th>Projected</th>
			<td>12</td>
			<td>12</td>
			<td>12</td>
			<td>12</td>
		</tr>
		<tr>
			<th>Actual</th>
			<td>2</td>
			<td>5</td>
			<td>8</td>
			<td>10</td>
		</tr>
		<tr>
			<th>Balance</th>
			<td>10</td>
			<td>7</td>
			<td>4</td>
			<td>2</td>
		</tr>
		<tr>
			<th>Members</th>
			<td>2</td>
			<td>2</td>
			<td>2</td>
			<td>2</td>
		</tr>
	</tbody>
</table></div>
"""


[[Component.Dependencies]]
ID = "core_hestiaUI"
Priority = "Compulsory"
Include = true


[[Component.Designers]]
Name = "(Holloway) Chew, Kean Ho"
Email = "me@hollowaykeanho.com"
Website = "https://www.hollowaykeanho.com"


[Component.References]
JS = ""
Go = ""
Rust = ""


[[Component.References.HTML]]
Type = "Minimum"
Description = """
The component uses W3C native 'table', 'thead', 'tr', 'th', 'tbody', and 'td'
syntaxes and a 'div' alignment container to construct a centered table. Without
the 'div' alignment container, the default is to occupy the entire width spacing
and present the table from left to right, which can be very akward if the
table's content is scarce. The following codes shall render itself minimally:
"""
Example = """
<div style='display:flex;justify-content:center;'><table>
	<thead>
		<tr>
			<th>...</th>
			<th>...</th>
			...
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>...</td>
			<td>...</td>
			...
		</tr>
		...
	</tbody>
</table></div>
"""


[[Component.References.HTML]]
Type = "2-Axis Headers"
Description = """
The component uses W3C native 'table', 'thead', 'tr', 'th', 'tbody', and 'td'
syntaxes and a 'div' alignment container to construct a centered table. Without
the 'div' alignment container, the default is to occupy the entire width spacing
and present the table from left to right, which can be very akward if the
table's content is scarce. For 2-axis headers, each row of the 'tbody' shall
contain a leading 'th' while 'thead' has an empty leading 'th' to compensate the
header column. The following codes shall render itself minimally:
"""
Example = """
<div style='display:flex;justify-content:center;'><table>
	<thead>
		<tr>
			<th></th>
			<th>...</th>
			<th>...</th>
			...
		</tr>
	</thead>
	<tbody>
		<tr>
			<th>...</th>
			<td>...</td>
			<td>...</td>
			...
		</tr>
		...
	</tbody>
</table></div>
"""


[[Component.References.CSS]]
Name = "--table-display"
Description = """
Affects the entire component's display mode value.
"""
Property = "display"
Default = "block"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--table-overflow"
Description = """
Affects the entire component's overflow mode value.
"""
Property = "overflow"
Default = "auto"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--table-margin"
Description = """
Affects the entire component's margin value.
"""
Property = "margin"
Default = "2rem auto"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--table-padding"
Description = """
Affects the entire component's padding value.
"""
Property = "padding"
Default = "0"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--table-min-width"
Description = """
Affects the entire component's minimum width value.
"""
Property = "min-width"
Default = "initial"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--table-max-width"
Description = """
Affects the entire component's maximum width value.
"""
Property = "max-width"
Default = "100%"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--table-min-height"
Description = """
Affects the entire component's minimum height value.
"""
Property = "min-height"
Default = "initial"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--table-max-height"
Description = """
Affects the entire component's maximum height value.
"""
Property = "max-height"
Default = "initial"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--table-border"
Description = """
Defines the table's border value for table cell and table headers.
"""
Property = "border"
Default = "1px solid var(--color-primary-900)"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--table-color"
Description = """
Affects the entire component's color value.
"""
Property = "color"
Default = "var(--body-color)"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--table-color-inverted"
Description = """
Affects the entire component's color value while operating in an inverted
environment (e.g. footer).
"""
Property = "color"
Default = "var(--color-primary-200)"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--table-color-print"
Description = """
Affects the entire component's color value in print mode.
"""
Property = "color"
Default = "var(--body-color-print)"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--table-background"
Description = """
Affects the component's value field's background value.
"""
Property = "background"
Default = "var(--body-background)"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--table-background-print"
Description = """
Affects the component's value field's background value in print mode.
"""
Property = "background"
Default = "var(--body-background-print)"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--table-cell-margin"
Description = """
Affects the component's all cells margin value.
"""
Property = "margin"
Default = "0"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--table-cell-padding"
Description = """
Affects the component's all cells padding value.
"""
Property = "padding"
Default = "1rem"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--table-cell-border"
Description = """
Affects the component's all cells border value.
"""
Property = "border"
Default = "var(--table-border)"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--table-thead-th-color"
Description = """
Affects the component's 'thead' container's color value.
"""
Property = "color"
Default = "var(--color-typography-100)"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--table-thead-th-background"
Description = """
Affects the component's 'thead' container's background value.
"""
Property = "background"
Default = "var(--color-primary-900)"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--table-tbody-th-color"
Description = """
Affects the component's 'tbody's 'th' header cell color value.
"""
Property = "color"
Default = "var(--color-typography-100)"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--table-tbody-th-background"
Description = """
Affects the component's 'tbody's 'th' header cell background value.
"""
Property = "background"
Default = "var(--color-primary-700)"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--table-tbody-td-focus-background"
Description = """
Affects the component's 'tbody's 'td' data cell background value while being
focused or hovered on.
"""
Property = "background"
Default = "var(--color-contrast-500)"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--table-tbody-td-odd-background"
Description = """
Affects the component's 'tbody's 'td' data cell background value while in odd
position.
"""
Property = "background"
Default = "transparent"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--table-tbody-td-even-background"
Description = """
Affects the component's 'tbody's 'td' data cell background value while in even
position.
"""
Property = "background"
Default = "var(--color-primary-50)"
Availability = "v1.0.0"
