[[Packages]]
Version = '1.1.0'
Summary = '''
Minor patch against version 1.0.0. It main focuses are to perform critical bug
fixes discovered from the deployment of its predecessor.
'''
Technologies = [
	"hestiaHUGO",
]
URL = 'v1p1p0'

[[Packages]]
Version = '1.0.0'
Summary = '''
First launch with Hugo theme supports. Its main focus is to enable web hosting
and presnetation of WASM-driven and conventional web content.
'''
Technologies = [
	"hestiaHUGO",
]
URL = 'v1p0p0'
