[i18n]
Title = 'Title'
Description = 'Description'




[i18n.Labels]
ID = 'ID'
ReleaseNote = 'ReleaseNote'
List = 'List'
Development = 'Development'
Latest = 'Latest'




[i18n.Introduction]
ID = 'introduction'
Title = 'Introduction'




[i18n.Catalog]
ID = 'catalog'
Title = 'Available Packages'
Description = '''
From the latest to the earliest.
'''
Label = 'Read More'
