[Metadata]
Name = 'DEB Changelog Update'
Description = """
Generating/Updating .deb persistent changelog files.
"""
Type = 'deb'

[Variables]
ChangelogFrom = 'origin/staging'
ChangelogTo = 'origin/main'

[FMTVariables]




[[Dependencies]]
Name = 'Git for Changelog Generation'
Condition = 'all-all'
Type = 'command'
Command = 'git'




[Changelog]
LineBreak = "\n"
Regex = ''

[[Changelog.CMD]]
Name = "Fetch All Local Remote Branches To The Latest"
Type = 'command'
Condition = [ 'all-all' ]
Source = 'git fetch --all'

[[Changelog.CMD]]
Name = "Get Changelog Data from Git Log Between Branches"
Type = 'command'
Condition = [ 'all-all' ]
Source = """git --no-pager log \
"{{- .ChangelogTo -}}..{{- .ChangelogFrom -}}" \
--pretty="format:%h %s"
"""
Save = "ChangelogEntries"




[Packages.linux-amd64]
OS = [ 'linux' ]
Arch = [ 'amd64' ]
Distribution = [
	'stable',
]
Changelog = '{{- .DataDir -}}/debian/changelog-{{- .PkgArch -}}'

[Packages.linux-arm64]
OS = [ 'linux' ]
Arch = [ 'arm64' ]
Distribution = [
	'stable',
]
Changelog = '{{- .DataDir -}}/debian/changelog-{{- .PkgArch -}}'

[Packages.linux-armhf]
OS = [ 'linux' ]
Arch = [ 'armhf' ]
Distribution = [
	'stable',
]
Changelog = '{{- .DataDir -}}/debian/changelog-{{- .PkgArch -}}'




[[CMD]]
Name = 'Placeholder'
Type = 'placeholder'
Condition = [ 'all-all' ]
Source = ''
Target = ''
