[Component]
Name = "ZORALab's Hestia Shields.io Badge UI Component"
Type = "badge"
ID = "badge-shields_hestiaUI"
Status = "Stable - Public"
Available = "v1.0.0"
Purpose = """
This UI component was primarily designed for displaying features and
recognitions in an attractive shields.io badge. It works natively so that the
content creator can focus on the writing rather than messing with styling.
"""
Example = """
<div class="badge">
	<p class="title">Achievement</p>
	<p class="value">Omega</p>
</div>
<div class="badge">
	<p class="title">Achievement</p>
	<p class="value">Founder</p>
</div>
<div class="badge">
	<p class="title">Achievement</p>
	<p class="value">Leader</p>
</div>
<div class="badge">
	<p class="title">Achievement</p>
	<p class="value">What else do you want?!</p>
</div>
"""


[[Component.Dependencies]]
ID = "core_hestiaUI"
Priority = "Compulsory"
Include = true


[[Component.Designers]]
Name = "(Holloway) Chew, Kean Ho"
Email = "me@hollowaykeanho.com"
Website = "https://www.hollowaykeanho.com"


[Component.References]
JS = ""
Go = ""
Rust = ""


[[Component.References.HTML]]
Type = "Minimum"
Description = """
The component uses '.badge' CSS class to denote a container is a badge
component default to shields.io design. Within the container, a '.title' CSS
class and a '.value' CSS class containers denote their respective badge parts.
"""
Example = """
<div class="badge">
	<p class="title">...</p>
	<p class="value">...</p>
</div>
"""


[[Component.References.CSS]]
Name = "--badge-margin"
Description = """
Affects the entire component's margin value.
"""
Property = "margin"
Default = ".2rem .5rem"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--badge-padding"
Description = """
Affects the entire component's padding value.
"""
Property = "padding"
Default = "0"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--badge-border"
Description = """
Affects the entire component's border value.
"""
Property = "border"
Default = "2px solid transparent"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--badge-border-radius"
Description = """
Affects the entire component's border radius value.
"""
Property = "border-radius"
Default = ".4rem"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--badge-width-shine"
Description = """
Affects the entire component's shining ray's width value.
"""
Property = "width"
Default = ".6rem"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--badge-box-shadow"
Description = """
Affects the entire component's box-shadow value.
"""
Property = "box-shadow"
Default = "0 .2rem 1rem transparent"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--badge-box-shadow-shine"
Description = """
Affects the entire component's box-shadow value when it is shining.
"""
Property = "box-shadow"
Default = "0 .2rem 1rem var(--badge-color-shine)"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--badge-color"
Description = """
Affects the entire component's color value.
"""
Property = "color"
Default = "var(--color-typography-50)"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--badge-color-shine"
Description = """
Affects the entire component's shining color value.
"""
Property = "color"
Default = "var(--color-contrast-400)"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--badge-color-print"
Description = """
Affects the entire component's color value in print mode.
"""
Property = "color"
Default = "var(--body-color-print)"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--badge-background"
Description = """
Affects the component's value field's background value.
"""
Property = "background"
Default = "var(--color-primary-400)"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--badge-background-print"
Description = """
Affects the component's value field's background value in print mode.
"""
Property = "background"
Default = "var(--body-background-print)"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--badge-timing"
Description = """
Affects the entire component's animation timing value.
"""
Property = "transition"
Default = "var(--timing-normal)"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--badge-timing-shine"
Description = """
Affects the entire component's shining animation timing value.
"""
Property = "transition"
Default = "1.3s"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--badge-title-margin"
Description = """
Affects the component's title margin value.
"""
Property = "margin"
Default = "0"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--badge-title-padding"
Description = """
Affects the component's title padding value.
"""
Property = "padding"
Default = ".5rem 1rem"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--badge-title-font-size"
Description = """
Affects the component's title font sizing value.
"""
Property = "font-size"
Default = "var(--body-font-size)"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--badge-title-text-transform"
Description = """
Affects the component's title text transformation value.
"""
Property = "text-transform"
Default = "uppercase"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--badge-title-text-align"
Description = """
Affects the component's title text alignment value.
"""
Property = "text-align"
Default = "left"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--badge-title-color"
Description = """
Affects the component's title color value.
"""
Property = "color"
Default = "var(--color-typography-50)"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--badge-title-background"
Description = """
Affects the component's title background value.
"""
Property = "background"
Default = "var(--color-typography-800)"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--badge-value-margin"
Description = """
Affects the component's value field margin value.
"""
Property = "margin"
Default = "0"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--badge-value-padding"
Description = """
Affects the component's value field padding value.
"""
Property = "padding"
Default = ".5rem 1rem"
Availability = "v1.0.0"
