[Metadata]
Name = 'GolangCI-Lint'
Description = """
Setup GolangCI-Lint static analysis tool for Go Programming Language.
"""
Type = 'https-download'




[Variables]
Version = '1.49.0'
BaseURL = 'https://github.com/golangci/golangci-lint/releases/download'

[FMTVariables]




# Supported OS and CPU Architectures program sources. The Key for supported
# OS and CPU complies to the format:
#	[Sources.{GOOS}-{GOARCH}]
# Only list out supported packages will do.
[Sources.all-all]
Format = 'tar.gz'
Archive = 'golangci-lint-{{- .Version -}}-{{- .ComputeSystem -}}.{{- .Format -}}'
URL = '{{- .BaseURL -}}/v{{- .Version -}}/{{- .Archive -}}'
Method = 'GET'
[Sources.all-all.Checksum]
Type = 'sha256'
Format = 'hex'
[Sources.all-all.headers]

[Sources.darwin-amd64.Checksum]
Value = '20cd1215e0420db8cfa94a6cd3c9d325f7b39c07f2415a02d111568d8bc9e271'

[Sources.darwin-arm64.Checksum]
Value = 'cabb1a4c35fe1dadbe5a81550a00871281a331e7660cd85ae16e936a7f0f6cfc'

[Sources.freebsd-386.Checksum]
Value = 'f834c3b09580cf763b5d30b0c33c83cb13d7a822b5ed5d724143f121ffe28c97'

[Sources.freebsd-amd64.Checksum]
Value = '4ca91c9f3aa79a71da441b7220a3e799365ff7a24caf9f04fcda12066c5ab0f7'

[Sources.freebsd-armv6.Checksum]
Value = '37de789245248eea375d05080e11b4662a08762c353752575167611e65658454'

[Sources.freebsd-armv7.Checksum]
Value = '3abed2bd3a8134b501fdc9cc9a0e60d616c86389e4fcdd1f79ceae7458974378'

[Sources.linux-386.Checksum]
Value = 'ef2860d90d83aee6713f697f23372cd93ac41a16439fdcb3c4ac86ba0f306860'

[Sources.linux-amd64.Checksum]
Value = '5badc6e9fee2003621efa07e385910d9a88c89b38f6c35aded153193c5125178'

[Sources.linux-arm64.Checksum]
Value = 'b57ed03d29b8ca69be9925edd67ea305b6013cd5c97507d205fbe2979f71f2b5'

[Sources.linux-armv6]
Archive = 'golangci-lint-{{- .Version -}}-linux-armv6.{{- .Format -}}'
[Sources.linux-armv6.Checksum]
Value = '4a41cff3af7f5304751f7bbf4ea617c14ebc1f88481a28a013e61b06d1f7102c'

[Sources.linux-armv7]
Archive = 'golangci-lint-{{- .Version -}}-linux-armv7.{{- .Format -}}'
[Sources.linux-armv7.Checksum]
Value = '14a9683af483ee7052dd0ce7d6140e0b502d6001bea3de606b8e7cce2c673539'

[Sources.linux-mips64.Checksum]
Value = '33edf757bc2611204fdb40b212900866a57ded4eea62c1b19c10bfc375359afa'

[Sources.linux-mips64le.Checksum]
Value = '280f7902f90d162566f1691a300663dd8db6e225e65384fe66b6fb2362e0b314'

[Sources.linux-ppc64le.Checksum]
Value = '103bcb7ce6c668e0a7e95e5c5355892d74f5d15391443430472e66d652906a15'

[Sources.linux-riscv64.Checksum]
Value = '4636ff9b01ddb18a2c1a953fc134207711b0a5d874d04ac66f915e9cfff0e8e0'

[Sources.linux-s390x.Checksum]
Value = '029e0844931a2d3edc771d67e17fe17928f04f80c1a9aa165160a543e8a7e8d4'

[Sources.windows-386]
Format = 'zip'
[Sources.windows-386.Checksum]
Value = 'e9cb6f691e62a4d8b28dd52d2eab57cca72acfd5083b3c5417a72d2eb64def09'

[Sources.windows-amd64]
Format = 'zip'
[Sources.windows-amd64.Checksum]
Value = 'd058dfb0c7fbd73be70f285d3f8d4d424192fe9b19760ddbb0b2c4b743b8656c'

[Sources.windows-arm64]
Format = 'zip'
[Sources.windows-arm64.Checksum]
Value = 'c049d80297228db7065eabeac5114f77f04415dcd9b944e8d7c6426d9dd6e9dd'

[Sources.windows-armv6]
Format = 'zip'
[Sources.windows-armv6.Checksum]
Value = 'ec9164bab7134ddb94f51c17fd37c109b0801ecd5494b6c0e27ca7898fbd7469'

[Sources.windows-armv7]
Format = 'zip'
[Sources.windows-armv7.Checksum]
Value = '68fd9e880d98073f436c58b6f6d2c141881ef49b06ca31137bc19da4e4e3b996'




[[CMD]]
Name = 'Delete Target for Installation'
Type = 'delete-recursive-quiet'
Condition = ['all-all']
Source = '{{- .BinDir -}}/golangci-lint'

[[CMD]]
Name = 'Install Golang-CI Linter'
Type = 'move'
Condition = [ 'all-all' ]
Source = '{{- .WorkingDir -}}/golangci-lint-{{- .Version -}}-{{ .SourceCompute }}/golangci-lint'
Target = '{{- .BinDir -}}/golangci-lint'




[Config]
linux = """
#!/bin/bash

_name="golangci-lint"

case $1 in
--stop)
	;;
*)
	if [ ! -z "$(type -p "$_name")" ]; then
		1>&2 printf "[ DONE  ] '$_name' is available.\\n"
	else
		1>&2 printf "[ ERROR ] '$_name' is missing.\\n"
	fi
	;;
esac
"""
