[Metadata]
Name = 'Rust'
Description = """
Setup Rust programming language for compiling Rust source codes.
"""
Type = 'https-download'




[Variables]
BaseURL = 'https://static.rust-lang.org/rustup'
Toolchain = 'none'
Profile = 'minimal'

[FMTVariables]
RustupPath = '{{- .BinDir -}}/rustUP'
CargoPath = '{{- .BinDir -}}/rustCARGO'




# Supported OS and CPU Architectures program sources. The Key for supported
# OS and CPU complies to the format:
#	[Sources.{GOOS}-{GOARCH}]
# Only list out supported packages will do.
[Sources.all-all]
Format = 'raw'
Archive = "rustup-init.sh"
URL = '{{- .BaseURL -}}/{{- .Archive -}}'
Method = 'GET'

[Sources.all-all.Checksum]
Type = 'sha256'
Format = 'hex'
Value = '173f4881e2de99ba9ad1acb59e65be01b2a44979d83b6ec648d0d22f8654cbce'




[[CMD]]
Name = 'Delete Rustup Target for Installation'
Type = 'delete-recursive-quiet'
Condition = ['all-all']
Source = '{{- .RustupPath -}}'

[[CMD]]
Name = 'Delete Cargo Target for Installation'
Type = 'delete-recursive-quiet'
Condition = ['all-all']
Source = '{{- .CargoPath -}}'

[[CMD]]
Name = 'Install Rust Programming Language'
Type = 'command'
Condition = ['all-all']
Source = """RUSTUP_HOME="{{- .RustupPath -}}" \
CARGO_HOME="{{- .CargoPath -}}" \
RUSTUP_TOOLCHAIN="{{- .Toolchain -}}" \
sh {{ .WorkingDir -}}/{{- .Archive }} -y \
"""




[Config]
linux = """
#!/bin/bash
export LOCAL_BIN="${LOCAL_BIN:-{{- .BinDir -}}}"
export RUSTUP_HOME="{{- .RustupPath -}}"
export CARGO_HOME="{{- .CargoPath -}}"
export PATH_RUST="${CARGO_HOME}/bin"

stop_rust() {
	PATH=:${PATH}:
	PATH=${PATH//:$PATH_RUST:/:}
	PATH=${PATH%:}

	unset RUSTUP_HOME CARGO_HOME PATH_RUST
}

case $1 in
--stop)
	stop_rust
	1>&2 printf "[ DONE  ] localized Rust stopped.\\n"
	;;
*)
	case :$PATH: in
	*:$PATH_RUST:*)
		;;
	*)
		export PATH="${PATH}:${PATH_RUST}"
		;;
	esac

	if [ ! -z "$(type -p rustc)" ] && \
		[ ! -z "$(type -p rustup)" ] && \
		[ ! -z "$(type -p cargo)" ]; then
		1>&2 printf "[ DONE  ] localized Rust started.\\n"
		rustup set profile {{ .Profile }}
	else
		1>&2 printf "[ ERROR ] localized Rust failed to initalized.\\n"
		stop_rust
	fi
	;;
esac
"""
