[Software]
Name = 'Hestia'
Command = 'hestia'
ID = 'hestia'
Version = 'v1.2.2'
Category = 'devel'
Suite = ''
Abstract = 'One Peaceful Frontend+Backend Software Library Suite.'
Description = """
ZORALab's Hestia focuses on unifying all common libraries and data structure
into 1 single repository for highest attributes of reusablity, smoother learning
curves, and a more wholesome tools alignments. Develop and learn advanced
products easily with less worries about supply chain problems.
"""
Website = 'https://hestia.zoralab.com/'



[Software.Contact]
Name = 'ZORALab Enterprise'
Email = [ 'hello@zoralab.com' ]




[Software.Maintainers.zoralab]
Name = 'ZORALab Enterprise'
Email = [ 'tech@zoralab.com' ]
[Software.Maintainers.zoralab.JointTime]
Year = '2022'




[Software.Contributors.zoralab]
Name = 'ZORALab Enterprise'
Email = [ 'tech@zoralab.com' ]
[Software.Contributors.zoralab.JointTime]
Year = '2022'




[Software.Sponsors.zoralab]
Name = 'ZORALab Enterprise'
Email = [ 'tech@zoralab.com' ]
[Software.Sponsors.zoralab.JointTime]
Year = '2022'
