[i18n]
[i18n.Labels]
Contributors = '贡献者'
Coverage = '覆盖范围'
Delivered = '成功运出'
Description = '大纲'
Developing = '开源着'
Features = '功能'
Files = '文件'
ID = 'ID'
Language = '语言'
Licenses = '许可证'
Name = '名字'
Planned = '计划里'
Programming = '编程语言'
Reason = '原因'
References = '参考'
Status = '状况'
Strengths = '强点'
Title = '标题'
Thumbnail = '缩略图'
Value = '据值'




[i18n.Introduction]
ID = '自介'
Title = '自介'




[i18n.WhyItMatters]
ID = "为何选择zoralab赫斯提亚"
Title = "为何选择zoralab赫斯提亚"
Description = '''
'''




[i18n.Uses]
ID = "所有用例"
Title = "所有用例"
Description = '''
所有实验成功、正在实验和将来设计的zoralab赫斯提亚用例。
'''




[i18n.Technologies]
ID = "所有科技支持"
Title = "所有科技支持"
Description = '''
我们所以可以运用zoralab赫斯提亚代码库支持的科技。
'''




[i18n.Features]
ID = "所有功能"
Title = "所有功能"
Description = '''
所有已经建设、正在开源和在计划中的zoralab赫斯提亚功能。
'''




[i18n.UnderConstruction]
Title = '注意'
Description = '''
这个支持功能现任还在研制中。
'''




[i18n.Contributors]
ID = '我们的贡献者'
Title = '我们的贡献者'
Description = '''
代码，现金赞助，艺术品和媒体产品 — 谢谢让这个工程可以成功实现！
'''




[i18n.Sponsors]
ID = '金钱赞助'
Title = '金钱赞助'
Description = '''
谢谢我们的金钱赞助者好让这个工程继续更新和研制：
'''




[i18n.Developers]
ID = '科技研制'
Title = '科技研制'
Description = '''
谢谢我们的科技研制者、测验者、和编辑者好让这个工程跟上一层楼：
'''




[i18n.Artists]
ID = '艺术和媒体产品设计师'
Title = '艺术和媒体产品设计师'
Description = '''
感谢我们的艺术和媒体产品设计师们美化这个工程：
'''




[i18n.Epilogue]
ID = '让我们开始吧'
Title = '让我们开始吧！'
Description = '''
信得过吧？我们有为您准备好的开始指南！欢迎进来和我们开始您的网络设计吧：
'''
URL = '/zh-hans/getting-started'
CTA = '开始指南'
