# PAGE METADATA
# =============
# Date fields.
#
# NOTE:
#   1. You can generate date easily on linux using '$ date' command.
#   2. If date field is left blank, the current time shall be used instead.
#   3. Date should ONLY comply to this pattern when manually constructed:
#                    Thu 21 Jul 2022 14:27:39 PM +08
[Date]
Created   = 'Tue 20 Dec 2022 12:49:49 PM +08'
Published = 'Tue 20 Dec 2022 12:49:49 PM +08'




# Content fields.
# NOTE:
#   1. For .Title, Hestia's string processing using page variables are allowed
#      and only limited to .Titles sub-fields.
#   2. For .Keywords, Hestia's string processing using page variables are
#      allowed but strongly discouraged.
[Content]
Title = "ZORALab赫斯提亚"
Keywords = [
	'网站',
	'科技',
	'PWA',
	'WASM',
	'代码库',
	'Hugo',
	'Go',
	'TinyGo',
	'Nim',
	'ZORALab',
	"ZORALab赫斯提亚",
]




# Description fields.
# NOTE:
#   1. Hestia's string processing using page variables are allowed.
#   2. The .Description.Pitch is at maximum 160 characters.
#   3. The .Description.Summary is at maximum of 250 characters.
#   4. All fields shall have their whitespace cleansed during the processing.
[Description]
Pitch = '从研制者制作给另一个研制者的一个可建好前端+后端的代码库。'
Summary = """\
这工程统一话所有的常用代码库获取可重用的数据结构，把学习过程简单化，和对齐一切的
工具。以后不需要再烦恼供应链的威胁和问题下放松地去研制和学习吧。
"""




# Redirect fields.
# NOTE:
#   1. Hestia's URL processing is allowed for .URL field.
#   2. .Delay timing sets the delay time before redirect. Setting to '0' means
#      an immediate redirect is requested.
#   3. Redirect is only available if .Enabled is set to 'true'.
#   4. Redirect.Language is to redirect the current page to its
#      language-specific page when Javascript is made available on client side
#      or fallback to default language.
[Redirect]
Delay = 0 # second
URL = ''
Enabled = false

[Redirect.Language]
Enabled = false




# Content Files' Sourcing Location
# NOTE:
#   1. To denote where are the content sources.
#   2. If you're sourcing from assets directory, prefix 'assets/'.
#   3. If you're sourcing from layouts directory, prefix 'layouts/'.
#   2. If you're sourcing from static directory, prefix 'static/'.
#   3. If you're sourcing from partial directory, prefix 'layouts/partials/'.
[Sources]
HTML = 'layouts/content/index.html'
JSON = 'layouts/content/index.json'
CSS = 'layouts/content/index.css'
JS = 'layouts/content/index.js'
LDJSON = '__content.hestiaLDJSON'
Contributors = '__contributors.toml'
Thumbnails = '__thumbnails.toml'
Languages = '__languages.toml'
Assets = 'layouts/content/assets.toml'
Components = 'layouts/content/components.toml'




# Data fields.
# NOTE:
#   1. List only the page-level data files. It can be in any of the following
#      formats: '.json', '.toml', or '.yaml'.
#   2. Hestia string processing is available and shall be processed prior to
#      dataset transformation.
#   3. Sequences of the .Data array dictates sequences of loading and overriding
#      (the latter shall overwrite the former for the same data fields).
#   4. The final processed dataset shall be served as main data content in
#      supported output format (e.g. index.json).
#   5. Missing data file shall be ignored.
#   6. To add more data files, simply duplicate and add more .Data array entry.
#      Example:
#                             [[data]]
#                             Filename = 'file1.json'
#
#                             [[data]]
#                             Filename = 'file2.toml'
[[Data]]
Filename = '__i18n.toml'
