[en]
languageCode = "en"
languageName = "English"
contentDir = "../../docs/en"
title = "ZORALab's Hestia"
[en.params]
description = """\
One peaceful library for building infinite possibilities.
"""

[zh-hans]
languageCode = "zh-hans"
languageName = "Chinese (Simplified)"
contentDir = "../../docs/zh-hans"
title = "ZORALab赫斯提亚"
[zh-hans.params]
description = """\
一个平静代码库来建设眼无限的可能。
"""
