[en]
languageCode = "en"
languageName = "English"
contentDir = "../../docs/en"

[en.params]
title = "ZORALab's Hestia"
description = """\
One peaceful library for building infinite possibilities.
"""




[zh-hans]
languageCode = "zh-hans"
languageName = "Chinese (Simplified)"
contentDir = "../../docs/zh-hans"

[zh-hans.params]
title = "ZORALab赫斯提亚"
description = """\
一个平静代码库来建设眼无限的可能。
"""
