[Component]
Name = "ZORALab's Hestia Drawer Divider UI Component"
Type = "nav"
ID = "drawer_hestiaUI"
Status = "Stable - Public"
Available = "v0.0.1"
Purpose = """
This UI component was primarily designed for providing an overlaying drawer
panel display across the main content. This is primarily designed for navigation
purposes but can also be used for other presentation objectives. The component
works natively without having complicated CSS classing, Javascript, or WASM
intervention and assistances. It is only responsible for layout orientation so
the developer can have full freedom to fill its content. Drawers can be pulled
open from left, right, or top directions.
"""
Example = """
<div class="note">
	<input id="...ID-A..." type="checkbox" checked>
	<label for="...ID-A...">NOTE</label>
	<p class="content">
		This site had already deployed the <code>drawer_hestiaUI</code>
		component as its primary navigation system. Please check them
		out instead. Deploying a dummy example drawer can confuse this
		page's navigation system.
	</p>
</div>
"""


[[Component.Dependencies]]
ID = "core_hestiaUI"
Priority = "Compulsory"
Include = true


[[Component.Designers]]
Name = "(Holloway) Chew, Kean Ho"
Email = "me@hollowaykeanho.com"
Website = "https://www.hollowaykeanho.com"


[Component.References]
JS = ""
Go = ""
Rust = ""


[[Component.References.HTML]]
Type = "Minimum (Left)"
Description = """
The component uses W3C's 'nav' syntax with '.left-drawer' CSS class for its
main container design. Inside, a 'checkbox type input' with an unique ID,
a W3C's 'label' syntax with '.trigger' CSS class targetting the input,
a W3C's 'label' syntax with '.overlay' CSS class targetting the input,
and a container with '.content' CSS class are required. Inside the 'label' with
'.trigger', an '.open' and a '.close' CSS classes denotes their character
changes during the open/closing state. Hence, to rendering itself minimally:
"""
Example = """
<nav class="left-drawer">
	<input id="...INPUT_ID_1..." type="checkbox" />
	<label class="trigger" for="...INPUT_ID_1...">
		<span class="open">☰</span>
		<span class="close">𝖷</span>
	</label>
	<label class="overlay" for="...INPUT_ID_1..."></label>
	<div class="content">
		...
	</div>
</nav>
"""

[[Component.References.HTML]]
Type = "Minimum (Right)"
Description = """
The component uses W3C's 'nav' syntax with '.right-drawer' CSS class for its
main container design. Inside, a 'checkbox type input' with an unique ID,
a W3C's 'label' syntax with '.trigger' CSS class targetting the input,
a W3C's 'label' syntax with '.overlay' CSS class targetting the input,
and a container with '.content' CSS class are required. Inside the 'label' with
'.trigger', an '.open' and a '.close' CSS classes denotes their character
changes during the open/closing state. Hence, to rendering itself minimally:
"""
Example = """
<nav class="right-drawer">
	<input id="...INPUT_ID_1..." type="checkbox" />
	<label class="trigger" for="...INPUT_ID_1...">
		<span class="open">☰</span>
		<span class="close">𝖷</span>
	</label>
	<label class="overlay" for="...INPUT_ID_1..."></label>
	<div class="content">
		...
	</div>
</nav>
"""

[[Component.References.HTML]]
Type = "Minimum (Top)"
Description = """
The component uses W3C's 'nav' syntax with '.top-drawer' CSS class for its
main container design. Inside, a 'checkbox type input' with an unique ID,
a W3C's 'label' syntax with '.trigger' CSS class targetting the input,
a W3C's 'label' syntax with '.overlay' CSS class targetting the input,
and a container with '.content' CSS class are required. Inside the 'label' with
'.trigger', an '.open' and a '.close' CSS classes denotes their character
changes during the open/closing state. Hence, to rendering itself minimally:
"""
Example = """
<nav class="top-drawer">
	<input id="...INPUT_ID_1..." type="checkbox" />
	<label class="trigger" for="...INPUT_ID_1...">
		<span class="open">☰</span>
		<span class="close">𝖷</span>
	</label>
	<label class="overlay" for="...INPUT_ID_1..."></label>
	<div class="content">
		...
	</div>
</nav>
"""

[[Component.References.HTML]]
Type = "Minimum (Permanent Topbar)"
Description = """
The component uses W3C's 'nav' syntax with '.top-drawer' CSS class for its
main container design. Inside, a 'checkbox type input' with an unique ID,
a W3C's 'label' syntax with '.trigger' CSS class targetting the input,
a W3C's 'label' syntax with '.overlay' CSS class targetting the input,
and a container with '.content' CSS class are required. Inside the 'label' with
'.trigger', an '.open' and a '.close' CSS classes denotes their character
changes during the open/closing state. Hence, to rendering itself minimally:
"""
Example = """
<nav class='top-drawer' style='--top-drawer-height: 7rem; --top-drawer-height-opened: 7rem;'>
	<input id="...INPUT_ID_1..." type="checkbox" checked />
	<div class="content">
		...
	</div>
</nav>
"""

[[Component.References.CSS]]
Name = "--drawer-trigger-z-index"
Description = """
Affects the component's '.trigger' label's z-index value.
"""
Property = "z-index"
Default = "calc(var(--z-index-max) - var(--z-index-nav-top))"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--drawer-z-index"
Description = """
Affects the entire component's z-index value.
"""
Property = "z-index"
Default = "calc(var(--z-index-max) - var(--z-index-nav))"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--drawer-overlay-z-index"
Description = """
Affects the component's '.overlay' label's z-index value.
"""
Property = "z-index"
Default = "calc(var(--z-index-max) - var(--z-index-nav-overlay))"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--left-drawer-width"
Description = """
Affects the '.left-drawer' entire component's width value when closed.
"""
Property = "width"
Default = "0"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--left-drawer-width-opened"
Description = """
Affects the '.left-drawer' entire component's width value when opened.
"""
Property = "width"
Default = "90vw"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--top-drawer-width"
Description = """
Affects the '.top-drawer' entire component's width value when closed.
"""
Property = "width"
Default = "100%"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--top-drawer-width-opened"
Description = """
Affects the '.top-drawer' entire component's width value when opened.
"""
Property = "width"
Default = "100%"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--right-drawer-width"
Description = """
Affects the '.right-drawer' entire component's width value when closed.
"""
Property = "width"
Default = "0"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--right-drawer-width-opened"
Description = """
Affects the '.right-drawer' entire component's width value when opened.
"""
Property = "width"
Default = "90w"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--left-drawer-height"
Description = """
Affects the '.left-drawer' entire component's height value when closed.
"""
Property = "height"
Default = "100%"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--left-drawer-height-opened"
Description = """
Affects the '.left-drawer' entire component's height value when opened.
"""
Property = "height"
Default = "100%"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--top-drawer-height"
Description = """
Affects the '.top-drawer' entire component's height value when closed.
"""
Property = "height"
Default = "0"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--top-drawer-height-opened"
Description = """
Affects the '.top-drawer' entire component's height value when opened.
"""
Property = "height"
Default = "90vh"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--right-drawer-height"
Description = """
Affects the '.right-drawer' entire component's height value when closed.
"""
Property = "height"
Default = "100%"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--right-drawer-height-opened"
Description = """
Affects the '.right-drawer' entire component's height value when opened.
"""
Property = "height"
Default = "100%"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--drawer-border"
Description = """
Affects the entire component's border value.
"""
Property = "border"
Default = "1rem solid transparent"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--drawer-border-opened"
Description = """
Affects the entire component's border value when opened.
"""
Property = "border"
Default = "1rem solid var(--drawer-color-primary)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--drawer-border-radius"
Description = """
Affects the entire component's border radius value.
"""
Property = "border-radius"
Default = ".5rem"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--left-drawer-border-radius"
Description = """
Affects the '.left-drawer' entire component's border radius value.
"""
Property = "border-radius"
Default = "0 var(--drawer-border-radius) var(--drawer-border-radius) 0"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--top-drawer-border-radius"
Description = """
Affects the '.top-drawer' entire component's border radius value.
"""
Property = "border-radius"
Default = "0 0 var(--drawer-border-radius) var(--drawer-border-radius)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--right-drawer-border-radius"
Description = """
Affects the '.right-drawer' entire component's border radius value.
"""
Property = "border-radius"
Default = "var(--drawer-border-radius) 0 0 var(--drawer-border-radius)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--drawer-color"
Description = """
Affects the entire component's color value.
"""
Property = "color"
Default = "var(--body-color-inverted)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--drawer-color-inverted"
Description = """
Affects the entire component's color value in an inverted environment
(e.g. footer).
"""
Property = "color"
Default = "var(--body-color)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--drawer-color-primary"
Description = """
Affects the entire component's primary color value.
"""
Property = "color"
Default = "var(--color-primary-600)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--drawer-overlay-color"
Description = """
Affects the component's '.overlay' container's color value.
"""
Property = "color"
Default = "transparent"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--drawer-overlay-background"
Description = """
Affects the component's '.overlay' container's background value.
"""
Property = "background"
Default = "rgba(0,0,0,.75)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--drawer-transition"
Description = """
Affects the entire component's animation timing value.
"""
Property = "transition"
Default = "var(--timing-normal)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--drawer-overlay-transition"
Description = """
Affects the component's '.overlay' container's animation timing value.
"""
Property = "transition"
Default = "var(--timing-fast)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--drawer-trigger-width"
Description = """
Affects the component's '.trigger' container's width value.
"""
Property = "width"
Default = "4.5rem"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--drawer-trigger-height"
Description = """
Affects the component's '.trigger' container's height value.
"""
Property = "height"
Default = "4.5rem"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--drawer-trigger-border"
Description = """
Affects the component's '.trigger' container's border value.
"""
Property = "border"
Default = "unset"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--left-drawer-trigger-border"
Description = """
Affects the '.left-drawer' component's '.trigger' container's border value.
"""
Property = "border"
Default = "unset"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--top-drawer-trigger-border"
Description = """
Affects the '.top-drawer' component's '.trigger' container's border value.
"""
Property = "border"
Default = "unset"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--right-drawer-trigger-border"
Description = """
Affects the '.right-drawer' component's '.trigger' container's border value.
"""
Property = "border"
Default = "unset"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--drawer-trigger-border-radius"
Description = """
Affects the component's '.trigger' container's border radius value. Used for
constructing border radius for each drawer type.
"""
Property = "border-radius"
Default = "50%"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--left-drawer-trigger-border-radius"
Description = """
Affects the '.left-drawer' component's '.trigger' container's border radius
value.
"""
Property = "border-radius"
Default = "0 var(--drawer-trigger-border-radius) var(--drawer-trigger-border-radius) 0"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--top-drawer-trigger-border-radius"
Description = """
Affects the '.top-drawer' component's '.trigger' container's border radius
value.
"""
Property = "border-radius"
Default = "0 0 var(--drawer-trigger-border-radius) var(--drawer-trigger-border-radius)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--right-drawer-trigger-border-radius"
Description = """
Affects the '.right-drawer' component's '.trigger' container's border radius
value.
"""
Property = "border-radius"
Default = "var(--drawer-trigger-border-radius) 0 0 var(--drawer-trigger-border-radius)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--right-drawer-trigger-box-shadow"
Description = """
Affects the '.right-drawer' component's '.trigger' container's box shadowing
value.
"""
Property = "box-shadow"
Default = "0 0 2rem var(--drawer-overlay-background)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--right-drawer-trigger-box-shadow-focus"
Description = """
Affects the '.right-drawer' component's '.trigger' container's box shadowing
value while being focused.
"""
Property = "box-shadow"
Default = "0 0 4rem var(--drawer-overlay-background)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--drawer-trigger-font-size"
Description = """
Affects the component's '.trigger' container's font size value.
"""
Property = "font-size"
Default = "2rem"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--drawer-trigger-font-style"
Description = """
Affects the component's '.trigger' container's font style value.
"""
Property = "font-style"
Default = "normal"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--drawer-trigger-transform-focus"
Description = """
Affects the component's '.trigger' container's transformation value while being
focused.
"""
Property = "transform"
Default = "scale(1.1)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--left-drawer-trigger-position-top"
Description = """
Affects the '.left-drawer' component's '.trigger' container's top position value.
"""
Property = "position-top"
Default = "50%"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--left-drawer-trigger-position-left"
Description = """
Affects the '.left-drawer' component's '.trigger' container's left position value.
"""
Property = "position-left"
Default = "0"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--left-drawer-trigger-position-bottom"
Description = """
Affects the '.left-drawer' component's '.trigger' container's bottom position value.
"""
Property = "position-bottom"
Default = "unset"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--left-drawer-trigger-position-right"
Description = """
Affects the '.left-drawer' component's '.trigger' container's right position value.
"""
Property = "position-right"
Default = "unset"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--left-drawer-trigger-transform"
Description = """
Affects the '.left-drawer' component's '.trigger' container's transformation value.
"""
Property = "transform"
Default = "translateY(-50%)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--top-drawer-trigger-position-top"
Description = """
Affects the '.top-drawer' component's '.trigger' container's top position value.
"""
Property = "position-top"
Default = "0"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--top-drawer-trigger-position-left"
Description = """
Affects the '.top-drawer' component's '.trigger' container's left position value.
"""
Property = "position-left"
Default = "0"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--top-drawer-trigger-position-bottom"
Description = """
Affects the '.top-drawer' component's '.trigger' container's bottom position value.
"""
Property = "position-bottom"
Default = "unset"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--top-drawer-trigger-position-right"
Description = """
Affects the '.top-drawer' component's '.trigger' container's right position value.
"""
Property = "position-right"
Default = "unset"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--top-drawer-trigger-transform"
Description = """
Affects the '.top-drawer' component's '.trigger' container's transformation value.
"""
Property = "transform"
Default = "unset"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--right-drawer-trigger-position-top"
Description = """
Affects the '.right-drawer' component's '.trigger' container's top position value.
"""
Property = "position-top"
Default = "50%"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--right-drawer-trigger-position-left"
Description = """
Affects the '.right-drawer' component's '.trigger' container's left position value.
"""
Property = "position-left"
Default = "unset"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--right-drawer-trigger-position-bottom"
Description = """
Affects the '.right-drawer' component's '.trigger' container's bottom position value.
"""
Property = "position-bottom"
Default = "unset"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--right-drawer-trigger-position-right"
Description = """
Affects the '.right-drawer' component's '.trigger' container's right position value.
"""
Property = "position-right"
Default = "0"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--right-drawer-trigger-transform"
Description = """
Affects the '.right-drawer' component's '.trigger' container's transformation value.
"""
Property = "transform"
Default = "translateY(-50%)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--drawer-trigger-color"
Description = """
Affects the component's '.trigger' container's color value.
"""
Property = "color"
Default = "var(--drawer-color-inverted)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--drawer-trigger-background"
Description = """
Affects the component's '.trigger' container's background value.
"""
Property = "background"
Default = "var(--drawer-color-primary)"
Availability = "v0.0.1"
