[Metadata]
Name = 'Archives'
Description = """
Monteur's .tar.gz and .zip packagers released to hosting repository.
"""
Type = 'archive'




[Variables]

[FMTVariables]




[[Dependencies]]




[Releases]
Target = '{{- .RootDir -}}/archives/releases'
Checksum = 'sha512'

[Releases.Data]
Path = '{{- .RootDir -}}/archives/releases'
Format = 'toml'

[Releases.Packages.all-all-hestiaGO]
OS = [ "all" ]
Arch = [ "all" ]
Source = '{{- .PackageDir -}}/hestiaGO-{{- .App.Version -}}-pack.tar.gz'

[Releases.Packages.all-all-hestiaRUST]
OS = [ "all" ]
Arch = [ "all" ]
Source = '{{- .PackageDir -}}/hestiaRUST-{{- .App.Version -}}-pack.tar.gz'

[Releases.Packages.all-all-hestiaHUGO]
OS = [ "all" ]
Arch = [ "all" ]
Source = '{{- .PackageDir -}}/hestiaHUGO-{{- .App.Version -}}-pack.tar.gz'




[[CMD]]
Name = "Placeholder"
Type = 'placeholder'
Condition = [ 'all-all' ]
Source = ''
Target = ''
