[Date]
Created = "Fri 29 Jul 2022 10:35:17 AM +08" # e.g.: "Thu 21 Jul 2022 04:27:39 PM +08"
Published = "Fri 29 Jul 2022 10:35:17 AM +08" # e.g.: "Thu 21 Jul 2022 04:27:39 PM +08"




[Content]
Title = "Render HTML Meta Alternative-Languages - HestiaHUGO's Partial Function | {{ .Titles.Site -}}"
Keywords = [
	"Alternative-Languages",
	"Meta",
	"HTML",
	"Render",
	"Functions",
	"Hestia",
	"Partials",
	"Layouts",
	"Specifications",
	"HestiaHUGO",
	"ZORALab's Hestia",
	"Official Website",
	"ZORALab Enterprise",
	"ZORALab",
]




[Description]
Pitch = """
Uniformly render HTML alternative languages meta tags with HestiaHUGO's
'html/meta/Alternate-Languages'.
"""
Summary = """
Renders HTML alternative languages meta tags uniformly with HestiaHUGO's
'html/meta/Alternative-Languages' internal partial function.
"""




[Redirect]
URL = ""
Delay = 0 # second
Enabled = false
