# PAGE SPECIFIC ROBOTS INSTRUCTIONS LIST
# ======================================
#
# Example:
#     [[Meta]]
#     Name = "googleBot"
#     Content = "noindex, nofollow"
[[Meta]]
Name = "googleBot"
Content = "noindex, nofollow"

[[Meta]]
Name = "robots"
Content = "noindex, nofollow"
