[Licenses.Code]
Name = "Apache License 2.0"
ID = "Apache-2.0"
Examples = "*.go, *.rs, *.toml, *.json, *.html, ..."
File = "{{- .URL.Current.Absolute -}}hestia-software-license.pdf"
Signature = "{{- .URL.Current.Absolute -}}hestia-software-license.pdf.asc"

[Licenses.Others]
Name = "ZORALab's Hestia Media License"
ID = ""
Examples = "*.jpg, *.webp, *.avif, *.png, *.m4a, ..."
URL = "{{- .URL.Current.Absolute -}}hestia-media-license.pdf"
Signature = "{{- .URL.Current.Absolute -}}hestia-media-license.pdf.asc"
