[i18n]
Title = 'Title'
Description = 'Description'




[i18n.Introduction]
ID = 'introduction'
Title = "Introduction"




[i18n.Documentations]
ID = 'documentations'
Title = 'Documentations'
Description = '''
All required legal documents for the entire ZORALab's Hestia Project in the
following table. Please read through ALL OF THEM thoroughly before use.
'''


[i18n.Documentations.Labels]
Type = 'TYPE'
PDF = 'PDF'
Signature = 'GPG SIGNATURE'
Key = 'GPG KEY'
Coverage = 'COVERAGE'
Examples = 'EXAMPLES'
Sources = "SOURCES"



[i18n.Guidelines]
ID = 'guidelines'
Title = 'Guidelines'
Description = '''
While ZORALab's Hestia Project permits you to have quite a large freedom to
perform your creation freely, its legal documentations are still very hostile to
some. We had prepared this simple guidelines just in case:
'''

[i18n.Guidelines.Labels]
Do = 'Please DO'
Dont = 'Please DO NOT'


[[i18n.Guidelines.DO]]
Value = '''
Only use the source codes from the ZORALab's Hestia Project. Anything that are
not codes (e.g. image, video, binary, audio, etc) are prohibited. If you need
them, contact the original artists or creators at our attribution list in the
landing page.
'''

[[i18n.Guidelines.DO]]
Value = '''
Attribute (or add credits) back to ZORALab's Hestia Project when you use the
library. A simple "Thanks to ZORALab's Hestia Project" with an URL backlink is
suffice.
'''

[[i18n.Guidelines.DO]]
Value = '''
Can use ZORALab's Hestia Project in your commerical use (e.g. building a
chargable app, whether directly or requesting donation) as long as you do the
attributions.
'''

[[i18n.Guidelines.DO]]
Value = '''
When referring a Copyleft effect source (e.g. GPL-2), ONLY: (1) try to read;
understand the algorithm; (2) produce an algorithm document; (3) remove the code
sources; (4) then based on the algorithm document and write a fresh new set of
codes. NEVER copy and paste directly.
'''

[[i18n.Guidelines.DO]]
Value = '''
When contributing back to upstream: please make sure your contributions are
compliant to the outbound licenses shown above. We are not allowed to accept
incompatible licenses like GPL-2, GPL-3, unknown, or worse: proprietary.
'''

[[i18n.Guidelines.DO]]
Value = '''
When contributing back to upstream: please make sure you reference all your
sources in the files' copyright headers (trace all the way back to its birth).
We do file-level licensing notice, not just LICENSE.md file for added defenses.
'''

[[i18n.Guidelines.DO]]
Value = '''
When contributing back to upstream: please make sure you references' info are
publicly obtainable (e.g. published portfolio website). Generally, the minimum
is only full name and contactable email address are required.
'''

[[i18n.Guidelines.DO]]
Value = '''
If your upstream contributions involve graphical work, only code-only SVG
vector graphics with no embedded or remote URL calls file type is accepted.
'''

[[i18n.Guidelines.DO]]
Value = '''
If your upstream contributions involving graphical work for documentations,
please ONLY source from free (as in price and use rights) like Pexels or Pixabay
and attribute the artists eventhough their licenses are permissive.
'''

[[i18n.Guidelines.DO]]
Value = '''
When contributing back to upstream involving graphical work for documentations:
please make sure you references' first contact MUST be a public website
and indicating the origin of your source (every artist's first actionable link
represents the source of info and his/her artworks).
'''

[[i18n.Guidelines.DO]]
Value = '''
When contributing back to upstream involving graphical work for documentations:
please make sure the graphics you use DO NOT contain any identifiable model
entity (requires a separate model release form legal document for each one).
Model includes identifiable owned non-human entites like pet animals or iconic
cases like the night shot of Effiel Tower.
'''

[[i18n.Guidelines.DO]]
Value = '''
Avoid AI generated artwork whenever possible. Please support the artists even
as little as attributions in the landing page.
'''

[[i18n.Guidelines.DO]]
Value = '''
Please respect your references' work, efforts, inbound licenses' terms and
conditions, and thier priacy.
'''

[[i18n.Guidelines.DONT]]
Value = '''
DO NOT USE the ZORALab's Hestia Project's source codes THEN CLAIM your entire
build is YOUR NOVEL DEVELOPMENT. Site-note: don't force us or anyone to publicly
snipe you; you bloodly dumb and idiotic pirate!
'''

[[i18n.Guidelines.DONT]]
Value = '''
DO NOT COPY PASTE your codes from anywhere without investigating its source of
origin or its references.
'''

[[i18n.Guidelines.DONT]]
Value = '''
DO NOT USE our pictures, audio, media files and artifacts from the sites/ and
the artworks/ directories. Go source them directly from the artists listed in
the landing page.
'''

[[i18n.Guidelines.DONT]]
Value = '''
DO NOT REFERENCE any closed-source documentations or engineering specification
(where general public cannot obtain without purchase or etc). We do not intend
to propogate unnecessary difficulties downstream.
'''

[[i18n.Guidelines.DONT]]
Value = '''
DO NOT USE graphical work involving model entities like human or identifiable
owned entities like pet animals for documentations WITHOUT all signed and
ratified Model Release Form legal documents made available publicly.
'''

[[i18n.Guidelines.DONT]]
Value = '''
DO NOT USE graphical work, regardless being legally or illegally from a paid
stocked photos that are non-distributable by default.
'''

[[i18n.Guidelines.DONT]]
Value = '''
DO NOT DISRESPECT your references' inbound licenses' terms and conditions and
their privacy.
'''




[i18n.COC]
ID = 'code-of-conduct'
Title = 'Code of Conduct'
Description = '''
This is a software library repository for software developers; not a baby
daycare, not a kindergarden, not a school, not a forum, not a political body,
and not your enforcement entity. Please BEHAVE & RESPECT. DO NOT FORCE US to
write a long restrictive human psychological mind-control manual here ⇒
PLEASE BRING YOUR OPINIONS AND POLITICS ELSEWHERE.
'''




[i18n.Epilogue]
ID = 'epilogue'
Title = 'Epilogue'
Description = '''
That's all for ZORALab's Hestia Project's licenses and all related legal
documents. When you're ready, we got you covered! Please feel free to start your
journey here:
'''
URL = '/en/getting-started'
CTA = 'Getting Started'
