[i18n]
Title = 'Title'
Name = 'Name'
Pitch = 'Pitch'
Thumbnails = 'Thumbnails'
URL = 'URL'
Guides = 'Guides'
User = 'User'
Developer = 'Developer'




[[Guides.User]]
ID = 'setup'
Name = 'Setup HestiaHUGO'
Pitch = 'Focus on just cleanly setting up your Hugo repository.'


[[Guides.User]]
ID = 'create-basic-page'
Name = 'Create A Page'
Pitch = 'Focus on creating a page using hestiaHUGO theme.'


[[Guides.User]]
ID = 'publish-github'
Name = 'Publish on GitHub'
Pitch = 'Focus on composing and publishing your sites to GitHub Pages.'


[[Guides.User]]
ID = 'publish-gitlab'
Name = 'Publish on GitLab'
Pitch = 'Focus on composing and publishing your sites to GitLab Pages.'


[[Guides.User]]
ID = 'publish-cloudflare'
Name = 'Publish on CloudFlare Pages'
Pitch = 'Focus on composing and publishing your sites to CloudFlare Pages.'





[[Guides.Developer]]
ID = 'develop-ui'
Name = 'Develop New UI'
Pitch = 'Focus on developing a new UI component using hestiaHUGO.'
