[Date]
Created = "Tue 26 Jul 2022 01:57:49 PM +08" # e.g.: "Thu 21 Jul 2022 04:27:39 PM +08"
Published = "Tue 26 Jul 2022 01:57:49 PM +08" # e.g.: "Thu 21 Jul 2022 04:27:39 PM +08"




[Content]
Title = "Render Open Graph HTML Metas - HestiaHUGO's Partial Function | {{ .Titles.Site -}}"
Keywords = [
	"Open Graph",
	"Meta",
	"HTML",
	"Render",
	"Functions",
	"Hestia",
	"Partials",
	"Layouts",
	"Specifications",
	"HestiaHUGO",
	"ZORALab's Hestia",
	"Official Website",
	"ZORALab Enterprise",
	"ZORALab",
]




[Description]
Pitch = """
Uniformly render Open Graph HTML metas with HestiaHUGO's 'html/meta/open-graph'
partial functions.
"""
Summary = """
Renders Open Graph HTML meta uniformly with HestiaHUGO's 'html/meta/open-graph'
internal partial function.
"""




[Redirect]
Delay = "0" # second
URL = ""
