[Component]
Name = "ZORALab's Hestia Error Note UI Component"
Type = "note"
ID = "note-error_hestiaUI"
Status = "Stable - Public"
Available = "v1.0.0"
Purpose = """
This UI component was primarily designed for notifying the visitor of an error
like matter requiring attention. It works natively so that the content creator
can focus on the writing rather than messing with styling.
"""
Example = """
<div class="note error">
	<input id="note-uid1" type="checkbox" checked>
	<label for="note-uid1">ERROR</label>
	<p class="content">
		This is an important error note for you to pay attention to.
		Just in case, you can minimize this note if required. It is set
		to open by default. Try click on the title.
	</p>
</div>
"""


[[Component.Dependencies]]
ID = "core_hestiaUI"
Priority = "Compulsory"
Include = true


[[Component.Dependencies]]
ID = "note_hestiaUI"
Priority = "Compulsory"
Include = true


[[Component.Designers]]
Name = "(Holloway) Chew, Kean Ho"
Email = "me@hollowaykeanho.com"
Website = "https://www.hollowaykeanho.com"


[Component.References]
JS = ""
Go = ""
Rust = ""


[[Component.References.HTML]]
Type = "Minimum"
Description = """
The component uses '.error' CSS class to denote a container is an error note
component on top of an existing '.note' CSS class container for rendering itself
minimally:
"""
Example = """
<div class="note error">
	... same as note_hestiaUI ...
</div>
"""


[[Component.References.CSS]]
Name = "--note-title-error-border-color"
Description = """
Affects the entire component's '.title' border color value when the note is
denoted as an error note.
"""
Property = "border-color"
Default = "var(--body-color-indicator-red)"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--note-title-error-color"
Description = """
Affects the component's '.title' color value when the note is denoted as an
error note.
"""
Property = "color"
Default = "#fff"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--note-title-error-indicator-color"
Description = """
Affects the component's open/close indicator color value when the note is
denoted as an error note.
"""
Property = "color"
Default = "#fff"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--note-title-error-background"
Description = """
Affects the component's '.title' background value when the note is denoted as
an error note.
"""
Property = "background"
Default = "var(--body-background-indicator-red-inverted)"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--note-content-error-color"
Description = """
Affects the component's '.content' color value when the note is denoted as an
error note.
"""
Property = "color"
Default = "var(--body-color-indicator-red)"
Availability = "v1.0.0"


[[Component.References.CSS]]
Name = "--note-content-error-background"
Description = """
Affects the component's '.content' background value when the note is denoted as
an error note.
"""
Property = "background"
Default = "var(--body-background-indicator-red)"
Availability = "v1.0.0"
