[Date]
Created = "Fri 29 Jul 2022 06:00:08 PM +08" # e.g.: "Thu 21 Jul 2022 04:27:39 PM +08"
Published = "Fri 29 Jul 2022 06:00:08 PM +08" # e.g.: "Thu 21 Jul 2022 04:27:39 PM +08"




[Content]
Title = "Render HTML Meta Formats - HestiaHUGO's Partial Function | {{ .Titles.Site -}}"
Keywords = [
	"Formats",
	"Meta",
	"HTML",
	"Render",
	"Functions",
	"Hestia",
	"Partials",
	"Layouts",
	"Specifications",
	"HestiaHUGO",
	"ZORALab's Hestia",
	"Official Website",
	"ZORALab Enterprise",
	"ZORALab",
]




[Description]
Pitch = """
Uniformly render HTML formats meta tags with HestiaHUGO's 'html/meta/Formats'.
"""
Summary = """
Renders HTML formats meta tags uniformly with HestiaHUGO's
'html/meta/Formats' internal partial function.
"""




[Redirect]
URL = ""
Delay = 0 # second
Enabled = false
