[Date]
Created = "Wed 27 Jul 2022 01:45:18 PM +08" # e.g.: "Thu 21 Jul 2022 04:27:39 PM +08"
Published = "Wed 27 Jul 2022 01:45:18 PM +08" # e.g.: "Thu 21 Jul 2022 04:27:39 PM +08"




[Content]
Title = "Render Thumbnails Data Debug Interface - HestiaHUGO's Partial Function | {{ .Titles.Site -}}"
Keywords = [
	"Thumbnails",
	"Debug",
	"HTML",
	"Render",
	"Functions",
	"Hestia",
	"Partials",
	"Layouts",
	"Specifications",
	"HestiaHUGO",
	"ZORALab's Hestia",
	"Official Website",
	"ZORALab Enterprise",
	"ZORALab",
]




[Description]
Pitch = """
Uniformly render Thumbnails data HTML debug interface with HestiaHUGO's
'html/debug/thumbnails'.
"""
Summary = """
Renders Thumbnails data into HTML debug interface uniformly with HestiaHUGO's
'html/debug/thumbnails' internal partial function.
"""




[Redirect]
Delay = "0" # second
URL = ""
