[Date]
Created = "Fri 22 Jul 2022 08:34:02 AM +08" # e.g.: "Thu 21 Jul 2022 04:27:39 PM +08"
Published = "Fri 22 Jul 2022 08:34:02 AM +08" # e.g.: "Thu 21 Jul 2022 04:27:39 PM +08"




[Content]
Title = "Render HTML Meta Title - HestiaHUGO's Partial Function | {{ .Titles.Site -}}"
Keywords = [
	"Title",
	"Meta",
	"HTML",
	"Render",
	"Functions",
	"Hestia",
	"Partials",
	"Layouts",
	"Specifications",
	"HestiaHUGO",
	"ZORALab's Hestia",
	"Official Website",
	"ZORALab Enterprise",
	"ZORALab",
]




[Description]
Pitch = """
Uniformly render HTML title with HestiaHUGO's 'html/meta/title'.
"""
Summary = """
Renders HTML Title uniformly with HestiaHUGO's 'html/meta/title' internal
partial function.
"""
Detailed = """
HestiaHUGO's internal partial function 'Title' is responsible for
rendering HTML output for HTML meta title code snippet. This is its technical
specification intended for future maintenances and development usage.
"""




[Redirect]
Delay = "0" # second
URL = ""
