[Component]
Name = "ZORALab's Hestia Card UI Component"
Type = "card"
ID = "card_hestiaUI"
Status = "Stable - Public"
Available = "v0.0.1"
Purpose = """
This UI component was primarily designed for displaying a visually attractive
content's summary in an organized manner responsive to any devices' screen
sizes. It was meant for reader's to have a visually appealing summary of a
subject. The component works natively without having complicated CSS classing,
Javascript, or WASM intervention and assistances. It is only responsible for
layout orientation so the developer can have full freedom to fill its content.
"""
Example = """
<figure class="card">
	<picture class="thumbnail">
		<img alt="card thumbnail" src="/img/demo/demo1-1200x1200.webp"
		width="300" height="300" />
	</picture>
	<div class="content">
		<p>
			Picture above is a Pexels licensed image contributed by
			Pixabay in Pexels.com. Please check them out below!
		</p>
	</div>
	<div class="actions">
		<a href="https://www.pexels.com/photo/green-leafed-tree-near-body-of-water-414102/"
			target="_blank"
			class="button">Image Source</a>
		<a href="https://www.pexels.com/@pixabay/"
			target="_blank"
			class="button">Pixabay</a>
		<a href="https://www.pexels.com/"
			target="_blank"
			class="button">Pexels</a>
		<a href="https://www.pexels.com/license/"
			target="_blank"
			class="button">Pexels License</a>
	</div>
</figure>
"""


[[Component.Dependencies]]
ID = "core_hestiaUI"
Priority = "Compulsory"
Include = true


[[Component.Designers]]
Name = "(Holloway) Chew, Kean Ho"
Email = "me@hollowaykeanho.com"
Website = "https://www.hollowaykeanho.com"


[Component.References]
JS = ""
Go = ""
Rust = ""


[[Component.References.HTML]]
Type = "Minimum"
Description = """
The component uses '.card', '.thumbnail', '.content', and '.actions' CSS classes
to render itself minimally:
"""
Example = """
<figure class="card">
	<picture class="thumbnail">
		...
	</picture>
	<div class="content">
		...
	</div>
	<div class="actions">
		...
	</div>
</figure>
"""

[[Component.References.CSS]]
Name = "--card-layout"
Description = "Affects the entire component's layout value."
Property = "grid"
Default = """
"thumbnail" minmax(0, var(--card-thumbnail-height))
"content" minmax(0, var(--card-content-height))
"actions" minmax(0, var(--card-actions-height))
/ var(--card-width)
"""
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-overflow"
Description = """
Affects the entire component's overflow mode value.
"""
Property = "overflow"
Default = "hidden"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-width"
Description = """
Affects the entire component's width value.
"""
Property = "width"
Default = "25rem"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-height"
Description = """
Affects the entire component's height value.
"""
Property = "height"
Default = "fit-content"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-margin"
Description = """
Affects the entire component's margin value.
"""
Property = "margin"
Default = "2rem"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-padding"
Description = """
Affects the entire component's padding value.
"""
Property = "padding"
Default = "0"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-border"
Description = """
Affects the entire component's border value.
"""
Property = "border"
Default = "1px solid var(--color-typography-300)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-border-focus"
Description = """
Affects the entire component's border value when focused or hovered.
"""
Property = "border"
Default = "1px solid var(--color-typography-300)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-border-radius"
Description = """
Affects the entire component's border radius value.
"""
Property = "border-radius"
Default = "1rem"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-box-shadow"
Description = """
Affects the entire component's box shadowing value.
"""
Property = "box-shadow"
Default = "0 1rem 2rem transparent"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-box-shadow-print"
Description = """
Affects the entire component's box shadowing value in print mode.
"""
Property = "box-shadow"
Default = "0 1rem 2rem var(--color-typography-800)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-box-shadow-focus"
Description = """
Affects the entire component's box shadowing value when focused or hovered.
"""
Property = "box-shadow"
Default = "0 1rem 2rem var(--color-typography-800)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-box-shadow-focus-inverted"
Description = """
Affects the entire component's box shadowing value when focused or hovered in
an inverted environment (e.g. footer).
"""
Property = "box-shadow"
Default = "0 1rem 2rem var(--color-typography-50)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-color"
Description = """
Affects the entire component's color value.
"""
Property = "color"
Default = "var(--body-color)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-color-print"
Description = """
Affects the entire component's color value in print mode.
"""
Property = "color"
Default = "var(--body-color-print)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-background"
Description = """
Affects the entire component's background value.
"""
Property = "background"
Default = "var(--body-background)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-background-print"
Description = """
Affects the entire component's background value in print mode.
"""
Property = "background"
Default = "var(--body-background-print)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-timing"
Description = """
Affects the entire component's animation timing value.
"""
Property = "transition"
Default = "var(--timing-normal)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-thumbnail-overflow"
Description = """
Affects the component's '.thumbnail' container's overflow value.
"""
Property = "overflow"
Default = "hidden"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-thumbnail-object-fit"
Description = """
Affects the component's '.thumbnail' container's object-fit value.
"""
Property = "object-fit"
Default = "cover"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-thumbnail-min-width"
Description = """
Affects the component's '.thumbnail' container's minimum width value.
"""
Property = "min-width"
Default = "100%"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-thumbnail-width"
Description = """
Affects the component's '.thumbnail' container's width value.
"""
Property = "width"
Default = "initial"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-thumbnail-max-width"
Description = """
Affects the component's '.thumbnail' container's maximum width value.
"""
Property = "max-width"
Default = "100%"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-thumbnail-min-height"
Description = """
Affects the component's '.thumbnail' container's minimum height value.
"""
Property = "min-height"
Default = "100%"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-thumbnail-height"
Description = """
Affects the component's '.thumbnail' container's height value.
"""
Property = "height"
Default = "max-content"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-thumbnail-max-height"
Description = """
Affects the component's '.thumbnail' container's maximum height value.
"""
Property = "max-height"
Default = "100%"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-thumbnail-margin"
Description = """
Affects the component's '.thumbnail' container's margin value.
"""
Property = "margin"
Default = "0"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-thumbnail-padding"
Description = """
Affects the component's '.thumbnail' container's padding value.
"""
Property = "padding"
Default = "0"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-content-overflow"
Description = """
Affects the component's '.content' container's overflow mode value.
"""
Property = "overflow"
Default = "auto auto"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-content-min-width"
Description = """
Affects the component's '.content' container's minimum width value.
"""
Property = "min-width"
Default = "initial"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-content-width"
Description = """
Affects the component's '.content' container's width value.
"""
Property = "width"
Default = "initial"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-content-max-width"
Description = """
Affects the component's '.content' container's maximum width value.
"""
Property = "max-width"
Default = "initial"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-content-min-height"
Description = """
Affects the component's '.content' container's minimum height value.
"""
Property = "min-height"
Default = "initial"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-content-height"
Description = """
Affects the component's '.content' container's height value.
"""
Property = "height"
Default = "auto"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-content-max-height"
Description = """
Affects the component's '.content' container's maximum height value.
"""
Property = "max-height"
Default = "initial"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-content-margin"
Description = """
Affects the component's '.content' container's margin value.
"""
Property = "margin"
Default = "0"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-content-padding"
Description = """
Affects the component's '.content' container's padding value.
"""
Property = "padding"
Default = "0"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-actions-overflow"
Description = """
Affects the component's '.actions' container's overflow mode value.
"""
Property = "overflow"
Default = "initial"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-actions-min-width"
Description = """
Affects the component's '.actions' container's minimum width value.
"""
Property = "min-width"
Default = "initial"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-actions-width"
Description = """
Affects the component's '.actions' container's width value.
"""
Property = "width"
Default = "initial"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-actions-max-width"
Description = """
Affects the component's '.actions' container's maximum width value.
"""
Property = "max-width"
Default = "initial"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-actions-min-height"
Description = """
Affects the component's '.actions' container's minimum height value.
"""
Property = "min-height"
Default = "initial"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-actions-height"
Description = """
Affects the component's '.actions' container's height value.
"""
Property = "height"
Default = "max-content"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-actions-max-height"
Description = """
Affects the component's '.actions' container's maximum height value.
"""
Property = "max-height"
Default = "initial"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-actions-margin"
Description = """
Affects the component's '.actions' container's margin value.
"""
Property = "margin"
Default = "0"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--card-actions-padding"
Description = """
Affects the component's '.actions' container's padding value.
"""
Property = "padding"
Default = "0"
Availability = "v0.0.1"
