# ╔══════════╗                                                      ╔══════════╗
# ║!! STOP !!║      Let the following be the default for Hestia     ║!! STOP !!║
# ╚══════════╝                                                      ╚══════════╝
ignoreFiles = [
	'(__.*)',
]
