[Component]
Name = "ZORALab's Hestia Note UI Component"
Type = "note"
ID = "note_hestiaUI"
Status = "Stable - Public"
Available = "v0.0.1"
Purpose = """
This UI component was primarily designed for notifying the visitor of an
attentive matter. It works natively so that the content creator can focus on the
writing rather than messing with styling.
"""
Example = """
<div class="note">
	<input id="note-uid1" type="checkbox" checked>
	<label for="note-uid1">A Moment Please</label>
	<p class="content">
		This is an important note for you to pay attention to. Just in
		case, you can minimize this note if required. It is set to open
		by default. Try click on the title.
	</p>
</div>
"""


[[Component.Dependencies]]
ID = "core_hestiaUI"
Priority = "Compulsory"
Include = true


[[Component.Designers]]
Name = "(Holloway) Chew, Kean Ho"
Email = "me@hollowaykeanho.com"
Website = "https://www.hollowaykeanho.com"


[Component.References]
JS = ""
Go = ""
Rust = ""


[[Component.References.HTML]]
Type = "Minimum"
Description = """
The component uses '.note' CSS class to denote a container is a note component;
a compulsory checkbox input (regardless both missing or available checked
property) equipped with an unique ID for matching label to defines the note's
open/close state; a container with '.content' CSS class for the content of the
note; and a label for title of the note for rendering itself minimally:
"""
Example = """
<div class="note">
	<input id="...ID-A..." type="checkbox" checked>
	<label for="...ID-A...">...</label>
	<p class="content">
		...
	</p>
</div>
"""


[[Component.References.CSS]]
Name = "--note-box-sizing"
Description = """
Affects the entire component's box sizing value.
"""
Property = "box-sizing"
Default = "border-box"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--note-margin"
Description = """
Affects the entire component's margin value.
"""
Property = "margin"
Default = "1.3rem auto"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--note-padding"
Description = """
Affects the entire component's margin value.
"""
Property = "padding"
Default = "0"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--note-min-width"
Description = """
Affects the entire component's minimum width value.
"""
Property = "min-width"
Default = "initial"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--note-width"
Description = """
Affects the entire component's width value.
"""
Property = "width"
Default = "100%"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--note-max-width"
Description = """
Affects the entire component's maximum width value.
"""
Property = "max-width"
Default = "100%"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--note-min-height"
Description = """
Affects the entire component's minimum height value.
"""
Property = "min-height"
Default = "initial"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--note-height"
Description = """
Affects the entire component's height value.
"""
Property = "height"
Default = "max-content"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--note-max-height"
Description = """
Affects the entire component's maximum height value.
"""
Property = "max-height"
Default = "initial"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--note-border"
Description = """
Affects the entire component's border value.
"""
Property = "border"
Default = "1px solid var(--color-primary-400)"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--note-border-radius"
Description = """
Affects the entire component's border-radius value.
"""
Property = "border-radius"
Default = ".5rem"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--note-timing"
Description = """
Affects the entire component's animation timing value.
"""
Property = "transition"
Default = "var(--timing-normal)"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--note-title-indicator-margin"
Description = """
Affects the component's open/close indicator margin spacing value.
"""
Property = "margin"
Default = "auto 1.5rem"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--note-title-font-size"
Description = """
Affects the component's title font sizing value.
"""
Property = "font-size"
Default = "2.5rem"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--note-title-font-style"
Description = """
Affects the component's title font styling value.
"""
Property = "font-style"
Default = "normal"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--note-title-font-weight"
Description = """
Affects the component's title font weight value.
"""
Property = "font-weight"
Default = "500"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--note-title-text-transform"
Description = """
Affects the component's title text transformation value.
"""
Property = "text-transform"
Default = "titlecase"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--note-title-text-align"
Description = """
Affects the component's title text alignment value.
"""
Property = "text-align"
Default = "left"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--note-title-color"
Description = """
Affects the component's title color value.
"""
Property = "color"
Default = "var(--body-color-inverted)"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--note-title-color-print"
Description = """
Affects the component's title color value in print mode.
"""
Property = "color"
Default = "var(--body-color-print)"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--note-title-indicator-color"
Description = """
Affects the component's open/close indicator color value.
"""
Property = "color"
Default = "var(--color-contrast-400)"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--note-title-indicator-color-print"
Description = """
Affects the component's open/close indicator color value in print mode.
"""
Property = "color"
Default = "var(--body-color-print)"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--note-title-background"
Description = """
Affects the component's title background value.
"""
Property = "background"
Default = "var(--color-primary-900)"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--note-title-background-print"
Description = """
Affects the component's title background value in print mode.
"""
Property = "background"
Default = "var(--body-background-print)"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--note-content-margin"
Description = """
Affects the component's content margin value.
"""
Property = "margin"
Default = "0"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--note-content-padding"
Description = """
Affects the component's content padding value.
"""
Property = "padding"
Default = "2rem"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--note-content-color"
Description = """
Affects the component's content color value.
"""
Property = "color"
Default = "var(--body-color)"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--note-content-color-print"
Description = """
Affects the component's content color value in print mode.
"""
Property = "color"
Default = "var(--body-color-print)"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--note-content-background"
Description = """
Affects the component's content background value.
"""
Property = "background"
Default = "var(--color-primary-100)"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--note-content-background-print"
Description = """
Affects the component's content background value in print mode.
"""
Property = "background"
Default = "var(--body-background-print)"
Availability = "v0.0.1"
