[i18n]
Title = '标题'
Description = '大纲'




[i18n.Labels]
ID = 'ID'
ReleaseNote = '发行说明'
List = '菜单'
Latest = '最新'
Development = '开发着'




[i18n.Introduction]
ID = '自介'
Title = '自介'




[i18n.Catalog]
ID = '菜单'
Title = '所有的软件包'
Description = '''
从最新到古前。
'''
Label = '了解更多'
