# PAGE-SPECIFIC CONTRIBUTORS
# ==========================
# QUICK NOTE:
#   1. Your contributor data shall be supplied in the .Data.Hestia.Creators/
#      directory. Here, you only list them out using their data filename as the
#      Key for this page and update their contribution.
#   2. Example entries:
#        [[Contributor]]
#        Key = 'Holloway'
#
#        [Contributor.Contribution]
#        Creation = true
#        Contact = true
#        Artwork = false
#        Knowledge = true
#        Editor = true
#        Developer = false
#        Maintainer = false
#        Producer = false
#        Provider = false
#        Publisher = false
#        Funder = false
#        Sponsor = false
#
#        [[Contributor]]
#        Key = 'CoryGalyna'
#
#        [Contributor.Contribution]
#        Creation = false
#        Contact = false
#        Artwork = false
#        Knowledge = false
#        Editor = true
#        Developer = false
#        Maintainer = false
#        Producer = false
#        Provider = false
#        Publisher = false
#        Funder = true
#        Sponsor = false
#
#        ...
