[[Nim]]
ID = 'setup-nim'
Title = 'Setup Nim'
Description = '''
The very beginning of the journey where you setup and configure the Nim Git
repository with hestiaNIM, ZORALab's Hestia Nim package from scratch.
'''
URL = 'setup-nim'
Label = 'Begin'
Include = false


[Nim.Image]
Name = ""
Decorative = true
Loading = 'lazy'
Width = "600"
Height = "600"
CORS = "anonymous"
Relationship = ""
Design = ""
Preload = ""
Control = false
Autoplay = false
Loop = false
Mute = false
Inline = false

[[Nim.Image.Sources]]
URL = "/img/logos/nim-1200x1200.svg"
Type = "image/svg+xml"
Media = "all"
Descriptor = '1x'
