[[Go]]
ID = 'setup-go'
Title = 'Setup Go'
Description = '''
The very beginning of the journey where you setup and configure the Go Git
repository with hestiaGO, ZORALab's Hestia Go module from scratch.
'''
URL = 'setup-go'
Label = 'Begin'
Include = false


[Go.Image]
Name = ""
Decorative = true
Loading = 'lazy'
Width = "600"
Height = "600"
CORS = "anonymous"
Relationship = ""
Design = ""
Preload = ""
Control = false
Autoplay = false
Loop = false
Mute = false
Inline = false

[[Go.Image.Sources]]
URL = "/img/logos/google-go-1200x1200.svg"
Type = "image/svg+xml"
Media = "all"
Descriptor = '1x'
