[[Go]]
ID = '设置go'
Title = '设置Go'
Description = '''
这是整个行程最早的步骤：您需要在Git存储库里从新设置和配置hestiaGo（ZORALab赫斯
提亚的Go模块）。
'''
URL = 'setup-go'
Label = '开始'
Include = false


[Go.Image]
Name = ""
Decorative = true
Loading = 'lazy'
Width = "600"
Height = "600"
CORS = "anonymous"
Relationship = ""
Design = ""
Preload = ""
Control = false
Autoplay = false
Loop = false
Mute = false
Inline = false

[[Go.Image.Sources]]
URL = "/img/logos/google-go-1200x1200.svg"
Type = "image/svg+xml"
Media = "all"
Descriptor = '1x'
