[[Nim]]
ID = '设置nim'
Title = '设置Nim'
Description = '''
这是整个行程最早的步骤：您需要在Git存储库里从新设置和配置hestiaNIM（ZORALab赫斯
提亚的Nim模块）。
'''
URL = 'setup-nim'
Label = '开始'
Include = false


[Nim.Image]
Name = ""
Decorative = true
Loading = 'lazy'
Width = "600"
Height = "600"
CORS = "anonymous"
Relationship = ""
Design = ""
Preload = ""
Control = false
Autoplay = false
Loop = false
Mute = false
Inline = false

[[Nim.Image.Sources]]
URL = "/img/logos/nim-1200x1200.svg"
Type = "image/svg+xml"
Media = "all"
Descriptor = '1x'
