[[Hugo]]
ID = '设置hugo'
Title = '设置Hugo'
Description = '''
这是整个行程最早的步骤：您需要在Hugo的Git存储库里从新设置和配置hestiaHUGO
（ZORALab赫斯提亚的Hugo模块）。
'''
URL = 'setup-hugo'
Label = '开始'
Include = true

[Hugo.Image]
Name = ""
Decorative = true
Loading = 'lazy'
Width = "600"
Height = "600"
CORS = "anonymous"
Relationship = ""
Design = ""
Preload = ""
Control = false
Autoplay = false
Loop = false
Mute = false
Inline = false

[[Hugo.Image.Sources]]
URL = "/img/logos/gohugo-1200x1200.svg"
Type = "image/svg+xml"
Media = "all"
Descriptor = '1x'




[[Hugo]]
ID = '建设简单和占位符性的Hugo网页'
Title = '建设简单和占位符性的Hugo网页'
Description = '''
通过建设简单网页来学习hesitaHUGO操作。
'''
URL = 'create-basic-and-placeholder-hugo-pages'
Label = '开始'
Include = true

[Hugo.Image]
Name = ""
Decorative = true
Loading = 'lazy'
Width = "600"
Height = "600"
CORS = "anonymous"
Relationship = ""
Design = ""
Preload = ""
Control = false
Autoplay = false
Loop = false
Mute = false
Inline = false

[[Hugo.Image.Sources]]
URL = "/img/logos/gohugo-1200x1200.svg"
Type = "image/svg+xml"
Media = "all"
Descriptor = '1x'
