# Hestia PAGE-LEVEL thumbnails configurations
# -------------------------------------------
[Contents.0]
Name = '{{- .Titles.Page -}}'
Decorative = false
Loading = 'lazy'
Width = '1200'
Height = '630'
CORS = 'anonymous'
Relationship = ''
Design = ''
Preload = ''
Control = false
Autoplay = false
Loop = false
Mute = false
Inline = false

[[Contents.0.Sources]]
URL = 'thumbnails-1200x630.jpg'
Type = 'image/jpeg'
Media = 'all'
Descriptor = '1x'

[Contents.0.Tracks.en]
URL = ''
Kind = 'subtitles'
Label = 'English'
Default = false




[Contents.1]
Name = '{{- .Titles.Page -}}'
Decorative = false
Loading = 'lazy'
Width = '1200'
Height = '1200'
CORS = 'anonymous'
Relationship = ''
Design = ''
Preload = ''
Control = false
Autoplay = false
Loop = false
Mute = false
Inline = false

[[Contents.1.Sources]]
URL = 'thumbnails-1200x1200.jpg'
Type = 'image/jpeg'
Media = 'all'
Descriptor = '1x'

[Contents.1.Tracks.en]
URL = ''
Kind = 'subtitles'
Label = 'English'
Default = false




[Contents.2]
Name = '{{- .Titles.Page -}}'
Decorative = false
Loading = 'lazy'
Width = '480'
Height = '480'
CORS = 'anonymous'
Relationship = ''
Design = ''
Preload = ''
Control = false
Autoplay = false
Loop = false
Mute = false
Inline = false

[[Contents.2.Sources]]
URL = 'thumbnails-480x480.jpg'
Type = 'image/jpeg'
Media = 'all'
Descriptor = '1x'

[Contents.2.Tracks.en]
URL = ''
Kind = 'subtitles'
Label = 'English'
Default = false
