[Date]
Created = "Sat 23 Jul 2022 03:53:45 PM +08" # e.g.: "Thu 21 Jul 2022 04:27:39 PM +08"
Published = "Sat 23 Jul 2022 03:53:45 PM +08" # e.g.: "Thu 21 Jul 2022 04:27:39 PM +08"




[Content]
Title = "Render HTML Meta Description - HestiaHUGO's Partial Function | {{ .Titles.Site -}}"
Keywords = [
	"Description",
	"Meta",
	"HTML",
	"Render",
	"Functions",
	"Hestia",
	"Partials",
	"Layouts",
	"Specifications",
	"HestiaHUGO",
	"ZORALab's Hestia",
	"Official Website",
	"ZORALab Enterprise",
	"ZORALab",
]




[Description]
Pitch = """
Uniformly render HTML description with HestiaHUGO's 'html/meta/description'.
"""
Summary = """
Renders HTML Title uniformly with HestiaHUGO's 'html/meta/description' internal
partial function.
"""




[Redirect]
URL = ""
Delay = 0 # second
Enabled = false
