[Component]
Name = "ZORALab's Hestia Unordered List UI Component"
Type = "list"
ID = "ulist_hestiaUI"
Status = "Stable - Public"
Available = "v0.0.1"
Purpose = """
This UI component was primarily designed for listing out items in an unordered
fashion working responsively in various display devices or browser sizes. It is
kept simple enough for customization without requiring too much localized
specifications.
"""
Example = """
<ul>
	<li>
		<p>Sun</p>
	</li>
	<li>
		<p>Earth</p>
		<ul style="--ulist-li-before-background:red;">
			<li><p>Human</p></li>
			<li><p>Trees</p></li>
		</ul>
	</li>
	<li>
		<p>Mars</p>
	</li>
</ul>
"""


[[Component.Dependencies]]
ID = "core_hestiaUI"
Priority = "Compulsory"
Include = true


[[Component.Designers]]
Name = "(Holloway) Chew, Kean Ho"
Email = "me@hollowaykeanho.com"
Website = "https://www.hollowaykeanho.com"


[Component.References]
JS = ""
Go = ""
Rust = ""


[[Component.References.HTML]]
Type = "Minimum"
Description = """
The component uses W3C compatible 'ul' and 'li' syntaxes to render itself
minimally:
"""
Example = """
<ul>
	<li>...</li>
	<li>...</li>
	<li>...</li>
</ul>
"""

[[Component.References.HTML]]
Type = "Minimum (Left Aligned List)"
Description = """
The component uses W3C compatible 'ul' and 'li' syntaxes alongside a
'.left-aligned' css class to render itself minimally:
"""
Example = """
<ul class='left-aligned'>
	<li>...</li>
	<li>...</li>
	<li>...</li>
</ul>
"""


[[Component.References.HTML]]
Type = "Compound"
Description = """
The component uses W3C compatible 'ul' and 'li' syntaxes to render itself
minimally alongside with its own sub-list (NOTE: please do customize the
sub-list's bullets using CSS classes to spell the differences):
"""
Example = """
<ul>
	<li>
		...
	</li>
	<li>
		...
		<ul style="--ulist-li-before-background:red;">
			<li>...</li>
			<li>...</li>
		</ul>
	</li>
	<li>
		...
	</li>
</ul>
"""


[[Component.References.HTML]]
Type = "Compound (Left-Aligned List)"
Description = """
The component uses W3C compatible 'ul' and 'li' syntaxes alongside a
'.left-aligned' css class to render itself minimally alongside with its own
sub-list:
"""
Example = """
<ul class='left-aligned'>
	<li>
		...
	</li>
	<li>
		...
		<ul class='left-aligned'>
			<li>...</li>
			<li>...</li>
		</ul>
	</li>
	<li>
		...
	</li>
</ul>
"""


[[Component.References.CSS]]
Name = "--ulist-spacing"
Description = """
Affects the list item's margin value uniquely when used in both default and
left-aligned list. You should only supply 1 sided value as the component shall
construct the margin in its own way.
"""
Property = "margin"
Default = "5rem"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--ulist-tab-spacing"
Description = """
Affects the list item's margin value uniquely for tab spacing when used in
left-aligned list. You should only supply 1 sided value as the component shall
construct the margin in its own way.
"""
Property = "margin"
Default = "6rem"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--ulist-display"
Description = """
Affects the entire component's display mode value.
"""
Property = "display"
Default = "block"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--ulist-margin"
Description = """
Affects the entire component's margin value.
"""
Property = "margin"
Default = "0"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--ulist-padding"
Description = """
Affects the entire component's padding value.
"""
Property = "padding"
Default = "0"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--ulist-text-align"
Description = """
Affects the entire component's text-align value.
"""
Property = "text-align"
Default = "initial"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--ulist-text-align-aligned-left"
Description = """
Affects the entire component's text-align value when used with '.left-aligned'
CSS class.
"""
Property = "text-align"
Default = "justify"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--ulist-li-margin"
Description = """
Affects the component's list item's margin value.
"""
Property = "margin"
Default = "var(--ulist-spacing) 0"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--ulist-li-margin-aligned-left"
Description = """
Affects the component's list item's margin value when used with '.left-aligned'
CSS class.
"""
Property = "margin"
Default = """
var(--ulist-spacing) 0 var(--ulist-spacing) var(--ulist-tab-spacing)
"""
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--ulist-li-padding"
Description = """
Affects the component's list item's padding value.
"""
Property = "padding"
Default = "0"
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--ulist-li-before-content"
Description = """
Affects the component's list item's bullet icon content value. Note that the
cancelled quotes are required to be part of the value.
"""
Property = "content"
Default = '\"Î¨\"'
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--ulist-li-before-display"
Description = """
Affects the component's list item's bullet icon display value.
"""
Property = "display"
Default = 'block'
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--ulist-li-before-margin"
Description = """
Affects the component's list item's bullet icon margin value.
"""
Property = "margin"
Default = '.5rem auto'
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--ulist-li-before-margin-aligned-left"
Description = """
Affects the component's list item's bullet icon margin value when the component
is used with '.left-aligned' value.
"""
Property = "margin"
Default = '.5rem 0'
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--ulist-li-before-padding"
Description = """
Affects the component's list item's bullet icon padding value.
"""
Property = "padding"
Default = '0'
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--ulist-li-before-border"
Description = """
Affects the component's list item's bullet icon border value.
"""
Property = "border"
Default = '1px solid transparent'
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--ulist-li-before-border-radius"
Description = """
Affects the component's list item's bullet icon border-radius value.
"""
Property = "border"
Default = '50%'
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--ulist-li-before-size"
Description = """
Affects the component's list item's bullet icon width and height value.
"""
Property = "width & height"
Default = '3rem'
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--ulist-li-before-font-size"
Description = """
Affects the component's list item's bullet icon font size value.
"""
Property = "font-size"
Default = '2rem'
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--ulist-li-before-font-weight"
Description = """
Affects the component's list item's bullet icon font weight value.
"""
Property = "font-weight"
Default = '700'
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--ulist-li-before-text-align"
Description = """
Affects the component's list item's bullet icon text alignment value.
"""
Property = "text-align"
Default = 'center'
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--ulist-li-before-color"
Description = """
Affects the component's list item's bullet icon color value.
"""
Property = "color"
Default = 'var(--color-typography-50)'
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--ulist-li-before-color-inverted"
Description = """
Affects the component's list item's bullet icon color value in an inverted
environment (e.g. footer).
"""
Property = "color"
Default = 'var(--color-typography-50)'
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--ulist-li-before-color-print"
Description = """
Affects the component's list item's bullet icon color value in print mode.
"""
Property = "color"
Default = 'var(--body-color-print)'
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--ulist-li-before-background"
Description = """
Affects the component's list item's bullet icon background value.
"""
Property = "color"
Default = 'var(--color-primary-400)'
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--ulist-li-before-background-inverted"
Description = """
Affects the component's list item's bullet icon background value in an inverted
environment (e.g. footer)
"""
Property = "color"
Default = 'var(--color-primary-400)'
Availability = "v0.0.1"


[[Component.References.CSS]]
Name = "--ulist-li-before-background-print"
Description = """
Affects the component's list item's bullet icon background value in print mode.
"""
Property = "color"
Default = 'var(--body-background-print)'
Availability = "v0.0.1"
