[Component]
Name = "ZORALab's Hestia Button UI Component"
Type = "button"
ID = "button_hestiaUI"
Status = "Stable - Public"
Available = "v0.0.1"
Purpose = """
This UI component was primarily designed for displaying a visually interactable
knob for reader to react upon that is responsive to any devices' screen sizes.
The component works natively without having complicated CSS classing,
Javascript, or WASM intervention and assistances.
"""
Example = """<br/>
<a href="https://www.zoralab.com" class="button" target="_blank">ZORALab</a>
<button>A Dub Button</button>
<button disabled>A Disabled Dub Button</button>
"""


[[Component.Dependencies]]
ID = "core_hestiaUI"
Priority = "Compulsory"
Include = true


[[Component.Designers]]
Name = "(Holloway) Chew, Kean Ho"
Email = "me@hollowaykeanho.com"
Website = "https://www.hollowaykeanho.com"


[Component.References]
JS = ""
Go = ""
Rust = ""


[[Component.References.HTML]]
Type = "Minimum"
Description = """
The component uses a '.button' CSS class to denotes the container is a button
for rendering itself minimally:
"""
Example = """
<a class="button" ...>...</a>
"""

[[Component.References.HTML]]
Type = "Native Button"
Description = """
The component works natively with the W3C compliant 'button' syntax, where
rendering itself minimally only needs:
"""
Example = """
<button>...</button>
"""

[[Component.References.HTML]]
Type = "Native Submit Input"
Description = """
The component works natively with the W3C compliant submit type 'input' syntax,
where rendering itself minimally only needs:
"""
Example = """
<input type="submit" ... />
"""

[[Component.References.HTML]]
Type = "Native Disabled Button"
Description = """
The component also works natively with disabled button.
"""
Example = """
<button disabled>...</button>
"""


[[Component.References.CSS]]
Name = "--button-display"
Description = """
Affects the entire component's display mode value.
"""
Property = "display"
Default = "inline-block"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--button-opacity"
Description = """
Affects the entire component's opacity value.
"""
Property = "opacity"
Default = "1"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--button-opacity-disabled"
Description = """
Affects the entire component's opacity value when disabled.
"""
Property = "opacity"
Default = ".3"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--button-margin"
Description = "Affects the entire component's margin value."
Property = "margin"
Default = ".5rem 1.2rem"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--button-padding"
Description = "Affects the entire component's padding value."
Property = "padding"
Default = "1.3rem"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--button-border"
Description = "Affects the entire component's border value."
Property = "border"
Default = "2px solid var(--button-color)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--button-border-radius"
Description = "Affects the entire component's border radius value."
Property = "border-radius"
Default = ".5rem"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--button-box-shadow"
Description = "Affects the entire component's box shadow value."
Property = "box-shadow"
Default = "0 .5rem 1rem var(--color-typography-400)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--button-color"
Description = "Affects the entire component's color value."
Property = "color"
Default = "var(--color-primary-600)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--button-color-inverted"
Description = """
Affects the entire component's color value when in an inverted environemnt
(e.g. footer).
"""
Property = "color"
Default = "var(--color-typography-100)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--button-color-print"
Description = "Affects the entire component's color value in print mode."
Property = "color"
Default = "var(--body-color-print)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--button-background"
Description = "Affects the entire component's background value."
Property = "color"
Default = "var(--body-background)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--button-background-print"
Description = "Affects the entire component's background value in print mode."
Property = "color"
Default = "var(--body-background-print)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--button-font-size"
Description = "Affects the entire component's font sizing value."
Property = "font-size"
Default = "var(--body-font-size)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--button-font-weight"
Description = "Affects the entire component's font weight value."
Property = "font-weight"
Default = "700"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--button-letter-spacing"
Description = "Affects the entire component's letter spacing value."
Property = "letter-spacing"
Default = ".1rem"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--button-text-align"
Description = "Affects the entire component's text alignment value."
Property = "text-align"
Default = "center"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--button-text-decoration"
Description = "Affects the entire component's text decoration value."
Property = "text-decoration"
Default = "none"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--button-text-transform"
Description = "Affects the entire component's text transformation value."
Property = "text-transform"
Default = "uppercase"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--button-overflow-wrap"
Description = "Affects the entire component's overflow wrapping behavior value."
Property = "overflow-wrap"
Default = "normal"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--button-word-break"
Description = "Affects the entire component's word breaking behavior value."
Property = "word-break"
Default = "normal"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--button-line-height"
Description = "Affects the entire component's line height behavior value."
Property = "line-height"
Default = "var(--body-line-height)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--button-transition"
Description = "Affects the entire component's animation behavior value."
Property = "transition"
Default = "var(--timing-rapid)"
Availability = "v0.0.1"

[[Component.References.CSS]]
Name = "--button-transform-focus"
Description = """
Affects the entire component's transformation animation value when focused or hovered.
"""
Property = "transform"
Default = "scale(1.1)"
Availability = "v0.0.1"
