[[Business]]
Thumbnail = 'readable-error-digest-600x600.webp'
ThumbnailType = 'image/webp'
Fallback = 'readable-error-digest-600x600.jpg'
Reason = 'Readable Error Digest'
Description = '''
Pinpoint error exactly where and why.
'''
Outcome = '''
Reduced complicated log jargons as many as possible.
'''




[[Business]]
Thumbnail = 'pwa-ready-600x600.webp'
ThumbnailType = 'image/webp'
Fallback = 'pwa-ready-600x600.jpg'
Reason = 'PWA Ready'
Description = '''
Analyzed, researched, tested, and simplified.
'''
Outcome = '''
Deploy PWA seamlessly and easily.
'''




[[Business]]
Thumbnail = 'flexible-ldjson-600x600.webp'
ThumbnailType = 'image/webp'
Fallback = 'flexible-ldjson-600x600.jpg'
Reason = 'Flexible LD+JSON Schema'
Description = '''
No more hackish integrations.
'''
Outcome = '''
Go wild with Schema.org SEO!
'''




[[Business]]
Thumbnail = 'go-compatible-template-codes-600x600.webp'
ThumbnailType = 'image/webp'
Fallback = 'go-compatible-template-codes-600x600.jpg'
Reason = 'Go Compatible Codes'
Description = '''
No more frankenstein-ing Markdown with shortcodes.
'''
Outcome = '''
Create Go compatible and reusable codes.
'''




[[Business]]
Thumbnail = 'compoentized-ui-600x600.webp'
ThumbnailType = 'image/webp'
Fallback = 'compoentized-ui-600x600.jpg'
Reason = 'Componentized UI'
Description = '''
Ready to cope with UI fashion trends.
'''
Outcome = '''
Easily design your content page with stable, continuously improved, learnable,
maintainable, reusable, and archivable UI.
'''




[[Business]]
Thumbnail = 'mobile-first-design-600x600.webp'
ThumbnailType = 'image/webp'
Fallback = 'mobile-first-design-600x600.jpg'
Reason = 'Mobile First Design'
Description = '''
Everyone uses mobile first.
'''
Outcome = '''
Proritizing wider audience and mobile experience.
'''




[[Business]]
Thumbnail = 'publishers-ready-600x600.webp'
ThumbnailType = 'image/webp'
Fallback = 'publishers-ready-600x600.jpg'
Reason = 'Publishers Ready'
Description = '''
No need external scripts for common publishers.
'''
Outcome = '''
Seamlessly served by GitHub Pages, GitLab Pages, and Cloudflare Pages.
'''




[[Business]]
Thumbnail = 'i18n-capable-600x600.webp'
ThumbnailType = 'image/webp'
Fallback = 'i18n-capable-600x600.jpg'
Reason = 'I18N Capable'
Description = '''
No more half-baked and confusing features.
'''
Outcome = '''
Recognizes visitors' language on-site; redirect accordingly; including 404 page.
'''




[[Business]]
Thumbnail = 'wholesome-html-600x600.webp'
ThumbnailType = 'image/webp'
Fallback = 'wholesome-html-600x600.jpg'
Reason = 'Wholesome HTML'
Description = '''
No more dirty page codes.
'''
Outcome = '''
Extremely friendly to page developer to debug output codes.
'''




[[Business]]
Thumbnail = 'wasm-ready-600x600.svg'
ThumbnailType = 'image/svg+xml'
Fallback = 'wasm-ready-600x600.jpg'
Reason = 'WASM Hosting Ready'
Description = '''
No more complications for using WASM.
'''
Outcome = '''
Seamless integrations with WASM deployments.
'''




[[Business]]
Thumbnail = 'favicon-generator-600x600.svg'
ThumbnailType = 'image/svg+xml'
Fallback = 'favicon-generator-600x600.jpg'
Reason = 'Icons and Favicons Ready'
Description = '''
No more 3rd-party generator dependencies.
'''
Outcome = '''
Natively generate Favicons, icons, MSFT Tile image, buttons, iPhones, Android,
browsers, etc.
'''




[[Business]]
Thumbnail = 'og-ready-1200x1200.webp'
ThumbnailType = 'image/webp'
Fallback = 'og-ready-1200x1200.jpg'
Reason = 'Social Media & Open Graph'
Description = '''
No more awkward looks on social media.
'''
Outcome = '''
Natively supports Open Graph, Twitter, Messengers, Whatsapp, Telegram, and
Signal.
'''




[[Purpose]]
Thumbnail = 'static-web-content.svg'
ThumbnailType = 'image/svg+xml'
Fallback = 'static-web-content.jpg'
Name = 'Static Web Content'
Description = '''
Classic static website using Hugo to present a web content.
'''
Action = 'https://www.hollowaykeanho.com/en/index.html'
Label = 'SHOWCASE'




[[Purpose]]
Thumbnail = 'json-data-server.svg'
ThumbnailType = 'image/svg+xml'
Fallback = 'json-data-server.jpg'
Name = 'Static JSON Data Server'
Description = '''
Like web content but serves .json data file alongside.
'''
Action = 'https://www.hollowaykeanho.com/en/index.json'
Label = 'SHOWCASE'




[[Purpose]]
Thumbnail = 'commerce-600x600.svg'
ThumbnailType = 'image/svg+xml'
Fallback = 'commerce-600x600.jpg'
Name = 'Commerce Payment Site'
Description = '''
Setup static site store and reputable payment gateway service providers!
'''
Action = 'https://store.hollowaykeanho.com/en/sponsorship/'
Label = 'SHOWCASE'




[[Purpose]]
Thumbnail = 'ui-designing.svg'
ThumbnailType = 'image/svg+xml'
Fallback = 'ui-designing.jpg'
Name = 'Web UI Component Design'
Description = '''
Simple enough to build and test an web UI component easily.
'''
Action = '/en/docs/hestiaui/'
Label = 'SHOWCASE'




[[Purpose]]
Thumbnail = 'app-distribution.svg'
ThumbnailType = 'image/svg+xml'
Fallback = 'app-distribution.jpg'
Name = 'Frontend App Distribution'
Description = '''
Builds frontend display applications easily via WASM+PWA.
'''
Action = ''
Label = ''



[i18n]
Title = 'Title'
Pitch = 'Pitch'
Reason = 'Reason'
Description = 'Description'
Outcome = 'Outcome'
Name = 'Name'
Business = 'Business'
Purpose = 'Purpose'
Type = 'Type'
Value = 'Value'
